"""
zones.py — Science zones and challenges.
"""

ZONE_ORDER = [
    "living_things",
    "sky_and_weather",
    "body_basics",
    "how_things_work",
]

ZONES = {
    "living_things": {
        "id": "living_things",
        "name": "The Garden of Living Things",
        "subtitle": "What's alive, and how can you tell?",
        "icon": "🌱",
        "description": "Discover what makes something alive",
        "level_required": 1,
        "challenges": [
            {
                "id": "lt_01",
                "title": "What Makes Something Alive?",
                "type": "quiz",
                "question": "Which of these is a living thing?",
                "lesson": "Living things grow, breathe, eat, and can have babies. Rocks do none of these — they're not alive!",
                "options": ["A rock", "A cloud", "A cat", "A shoe"],
                "answer": "c",
                "hints": ["Does it grow? Does it breathe? Does it eat?", "A cat grows, eats, and has kittens — it's alive!"],
                "xp": 30,
            },
            {
                "id": "lt_02",
                "title": "Plants Are Alive!",
                "type": "quiz",
                "question": "How do plants make their own food?",
                "lesson": "Plants make food from [bold yellow]sunlight, water, and air[/bold yellow]. This is called photosynthesis. That's why plants grow toward the light!",
                "options": ["They eat bugs", "They use sunlight, water, and air", "They get food from stores", "They eat other plants"],
                "answer": "b",
                "hints": ["Have you noticed how plants grow toward windows?", "Sun + water + air = food for plants!"],
                "xp": 30,
            },
            {
                "id": "lt_03",
                "title": "Animal or Plant?",
                "type": "quiz",
                "question": "What is the main difference between animals and plants?",
                "lesson": "Animals [bold yellow]move around[/bold yellow] to find food. Plants [bold yellow]stay in one place[/bold yellow] and make their own food from sunlight.",
                "options": ["Animals are bigger", "Animals move around to find food", "Plants are alive but animals aren't", "Animals live outside"],
                "answer": "b",
                "hints": ["Can a tree walk to the kitchen for a snack?", "Animals move! Plants stay put and make their own food."],
                "xp": 30,
            },
            {
                "id": "lt_04",
                "title": "Life Cycles",
                "type": "quiz",
                "question": "What comes after an egg in a frog's life cycle?",
                "lesson": "A frog's life: egg → [bold yellow]tadpole[/bold yellow] → frog. The tadpole swims like a fish and slowly grows legs!",
                "options": ["A frog right away", "A tadpole", "A butterfly", "A baby bird"],
                "answer": "b",
                "hints": ["Frogs start in water as babies — have you seen tadpoles?", "Egg → tadpole → frog!"],
                "xp": 35,
            },
            {
                "id": "lt_boss",
                "title": "Why Do Leaves Change Color?",
                "type": "quiz",
                "question": "Why do leaves turn red and orange in autumn?",
                "lesson": "In summer, leaves are full of [bold yellow]green chlorophyll[/bold yellow] which makes food. In autumn, days get shorter, trees stop making food, the green fades — and the hidden red, orange, and yellow colors show through!",
                "options": ["They get cold and freeze", "They stop making food and the green color fades away", "They get painted by the wind", "They are sick"],
                "answer": "b",
                "hints": ["The colors were hiding all along under the green!", "Leaves have red and yellow pigments — we just can't see them in summer."],
                "xp": 70,
                "is_boss": True,
            },
        ],
    },

    "sky_and_weather": {
        "id": "sky_and_weather",
        "name": "The Sky Watchers",
        "subtitle": "Sun, clouds, seasons, and storms",
        "icon": "☁️",
        "description": "Understand weather and the sky",
        "level_required": 2,
        "challenges": [
            {
                "id": "sw_01",
                "title": "Why Does the Sun Rise?",
                "type": "quiz",
                "question": "Why does the sun seem to move across the sky each day?",
                "lesson": "The sun doesn't move — [bold yellow]the Earth spins![/bold yellow] As our planet rotates, the sun appears to rise in the east, move across the sky, and set in the west.",
                "options": ["The sun walks across the sky", "The Earth spins around", "The clouds push the sun", "The moon moves the sun"],
                "answer": "b",
                "hints": ["The Earth is spinning right now — you just can't feel it!", "Earth rotates once every 24 hours — that's why we have day and night."],
                "xp": 30,
            },
            {
                "id": "sw_02",
                "title": "The Four Seasons",
                "type": "quiz",
                "question": "Why is summer warmer than winter?",
                "lesson": "In summer, the sun is [bold yellow]higher in the sky[/bold yellow] and shines more directly on us, giving more warmth. In winter, the Earth is tilted away from the sun, so sunlight hits at an angle and feels weaker.",
                "options": ["The sun is closer in summer", "The Earth tilts toward the sun in summer", "There are more clouds in winter", "The moon blocks the sun in winter"],
                "answer": "b",
                "hints": ["It's not about distance — it's about the angle!", "Earth's tilt changes how directly the sun hits us."],
                "xp": 35,
            },
            {
                "id": "sw_03",
                "title": "Where Does Rain Come From?",
                "type": "quiz",
                "question": "How does rain form?",
                "lesson": "The sun heats water in oceans and lakes. The water rises as invisible vapor, cools high up, and forms [bold yellow]clouds[/bold yellow]. When enough water collects, it falls as rain. Then the cycle starts again!",
                "options": ["Clouds are bags of water that pop", "Water evaporates, forms clouds, then falls as rain", "The sky makes new water", "Mountains push water into the sky"],
                "answer": "b",
                "hints": ["Have you seen steam from a hot cup? Water turning to vapor is similar!", "It's a cycle: water evaporates → forms clouds → rains → evaporates again."],
                "xp": 35,
            },
            {
                "id": "sw_04",
                "title": "What Is a Cloud?",
                "type": "quiz",
                "question": "What are clouds made of?",
                "lesson": "Clouds are made of [bold yellow]billions of tiny water droplets[/bold yellow] (or ice crystals) floating in the sky. They look white and fluffy but up close they look just like fog!",
                "options": ["Cotton fluff", "Smoke", "Tiny water droplets or ice crystals", "Dust and dirt"],
                "answer": "c",
                "hints": ["Have you ever walked through fog? That's basically a cloud at ground level!", "Tiny drops of water floating in air = cloud!"],
                "xp": 30,
            },
            {
                "id": "sw_boss",
                "title": "Why Is the Sky Blue?",
                "type": "quiz",
                "question": "Why does the sky look blue during the day?",
                "lesson": "Sunlight is actually [bold yellow]all colors mixed together[/bold yellow]. When it hits the atmosphere, blue light bounces around the most (it scatters), filling the whole sky with blue. At sunset, the light has to travel through more air, so the blue scatters away and we see red and orange!",
                "options": ["The ocean reflects blue upward", "Blue light scatters more through the atmosphere", "The sky is made of blue water", "Stars are blue"],
                "answer": "b",
                "hints": ["Sunlight has all colors — a rainbow proves it!", "Blue light bounces around in the atmosphere more than other colors."],
                "xp": 70,
                "is_boss": True,
            },
        ],
    },

    "body_basics": {
        "id": "body_basics",
        "name": "The Amazing Body",
        "subtitle": "Your body is working right now",
        "icon": "❤️",
        "description": "Understand your senses and how your body works",
        "level_required": 3,
        "challenges": [
            {
                "id": "bb_01",
                "title": "The Five Senses",
                "type": "quiz",
                "question": "How many senses does a human have? What are they?",
                "lesson": "Five senses: [bold yellow]sight, hearing, smell, taste, and touch[/bold yellow]. Together they help your brain understand the world around you.",
                "options": ["3 — sight, hearing, touch", "4 — sight, hearing, smell, taste", "5 — sight, hearing, smell, taste, touch", "6 — including a sixth sense"],
                "answer": "c",
                "hints": ["Use your fingers: eyes, ears, nose, tongue, skin!", "S-H-S-T-T: Sight, Hearing, Smell, Taste, Touch"],
                "xp": 30,
            },
            {
                "id": "bb_02",
                "title": "Your Heart",
                "type": "quiz",
                "question": "What does your heart do?",
                "lesson": "Your heart is a [bold yellow]pump[/bold yellow]. It beats about 70 times per minute, pushing blood through your entire body — delivering food and oxygen to every part of you!",
                "options": ["It stores energy like a battery", "It pumps blood through your whole body", "It controls your thoughts", "It makes you breathe"],
                "answer": "b",
                "hints": ["Put your hand on your chest — can you feel it beating?", "Your heart pumps blood everywhere!"],
                "xp": 30,
            },
            {
                "id": "bb_03",
                "title": "Breathing",
                "type": "quiz",
                "question": "Why do we breathe?",
                "lesson": "We breathe to get [bold yellow]oxygen[/bold yellow] into our blood. Our bodies use oxygen to turn food into energy. We breathe out carbon dioxide — the waste product.",
                "options": ["To cool ourselves down", "To get oxygen our bodies need for energy", "To make our voices work", "To smell things"],
                "answer": "b",
                "hints": ["Without oxygen, your body can't turn food into energy!", "In: oxygen. Out: carbon dioxide."],
                "xp": 30,
            },
            {
                "id": "bb_04",
                "title": "What Do Bones Do?",
                "type": "quiz",
                "question": "How many bones does an adult human body have?",
                "lesson": "Adult humans have [bold yellow]206 bones[/bold yellow]. Babies are born with about 270 smaller bones that fuse together as they grow. Bones give your body its shape, protect your organs, and let you move!",
                "options": ["26", "106", "206", "306"],
                "answer": "c",
                "hints": ["It's more than 100 but less than 300!", "206 bones hold your whole body together!"],
                "xp": 35,
            },
            {
                "id": "bb_boss",
                "title": "Why Do We Need Sleep?",
                "type": "quiz",
                "question": "Why is sleep so important for your body?",
                "lesson": "While you sleep, your [bold yellow]brain sorts memories[/bold yellow], your [bold yellow]body grows and repairs itself[/bold yellow], and your [bold yellow]immune system gets stronger[/bold yellow]. Without enough sleep, it's hard to learn, remember things, or feel well. Sleep is when your body does its best work!",
                "options": ["So we don't get bored at night", "So our brain and body can grow, repair, and process memories", "To save energy like a phone", "Because it gets dark outside"],
                "answer": "b",
                "hints": ["Think about how you feel after a bad night's sleep!", "Your brain and body do their repair work while you rest."],
                "xp": 70,
                "is_boss": True,
            },
        ],
    },

    "how_things_work": {
        "id": "how_things_work",
        "name": "The Workshop of Wonders",
        "subtitle": "Cause, effect, and simple machines",
        "icon": "⚙️",
        "description": "Discover how forces and simple machines work",
        "level_required": 4,
        "challenges": [
            {
                "id": "hw_01",
                "title": "Gravity",
                "type": "quiz",
                "question": "Why do things fall down when you drop them?",
                "lesson": "[bold yellow]Gravity[/bold yellow] is a force that pulls everything toward the Earth. The bigger an object, the stronger its gravity. Earth is so big, it pulls everything toward its center — so 'down' always means toward the ground!",
                "options": ["Because the air pushes them down", "Because gravity pulls everything toward Earth", "Because they're heavy", "Because of the wind"],
                "answer": "b",
                "hints": ["What holds you on the ground? Why doesn't the moon float away?", "Gravity is a pull between objects — bigger objects pull harder!"],
                "xp": 30,
            },
            {
                "id": "hw_02",
                "title": "A Ramp Helps",
                "type": "quiz",
                "question": "Why is it easier to push a heavy box up a ramp than to lift it straight up?",
                "lesson": "A [bold yellow]ramp[/bold yellow] (also called an inclined plane) is a simple machine. It spreads the work over a longer distance, so each step takes less force. Less force needed at once = easier!",
                "options": ["The ramp makes the box lighter", "The ramp makes the box slide", "The ramp spreads the work over a longer distance, needing less force at once", "Ramps are slippery"],
                "answer": "c",
                "hints": ["Think about loading ramps trucks use — why are they so long?", "A ramp trades distance for force: go further but push less hard!"],
                "xp": 35,
            },
            {
                "id": "hw_03",
                "title": "Shadows",
                "type": "quiz",
                "question": "How is a shadow made?",
                "lesson": "A shadow forms when a [bold yellow]solid object blocks light[/bold yellow]. Light travels in straight lines and can't bend around corners — so where the object blocks it, a dark area (shadow) appears behind it.",
                "options": ["The object absorbs the sun's color", "The object blocks light from reaching the surface behind it", "Shadows are reflections", "Dark air collects behind objects"],
                "answer": "b",
                "hints": ["On a sunny day, face the sun — where is your shadow?", "Light travels straight. When something blocks it, a shadow forms!"],
                "xp": 30,
            },
            {
                "id": "hw_04",
                "title": "Magnets",
                "type": "quiz",
                "question": "A magnet will attract (pull toward itself) which of these?",
                "lesson": "Magnets attract [bold yellow]iron and steel[/bold yellow]. They don't attract plastic, wood, glass, or most other materials. That's why fridges use magnets but your wooden desk doesn't stick to them!",
                "options": ["A plastic bottle", "A wooden pencil", "A steel paper clip", "A glass cup"],
                "answer": "c",
                "hints": ["Think about what sticks to a refrigerator!", "Iron and steel are attracted to magnets — most other materials aren't."],
                "xp": 30,
            },
            {
                "id": "hw_boss",
                "title": "Sink or Float?",
                "type": "quiz",
                "question": "A giant steel ship weighs thousands of tons, but it floats. A small steel coin sinks. Why?",
                "lesson": "An object floats if it displaces (pushes aside) water that weighs [bold yellow]more than the object itself[/bold yellow]. The hollow ship pushes aside a lot of water. The coin is solid and small, so the water it pushes weighs less than the coin — so it sinks!",
                "options": ["Ships are magic", "Ships are made of lighter steel", "The ship's hollow shape pushes aside more water than the coin", "The ocean is saltier near ships"],
                "answer": "c",
                "hints": ["What happens if you fill a bowl with water and put it in more water?", "It's about the space the object takes up, not just its weight!"],
                "xp": 80,
                "is_boss": True,
            },
        ],
    },
}
