"""
zones.py — Number zones and challenges for the Numbers skill pack.
"""

ZONE_ORDER = [
    "counting_hills",
    "addition_meadow",
    "subtraction_valley",
    "shape_forest",
    "time_tower",
]

ZONES = {
    "counting_hills": {
        "id": "counting_hills",
        "name": "The Counting Hills",
        "description": "Count to 100 and understand number order",
        "level_required": 1,
        "challenges": [
            {
                "id": "ch_01",
                "title": "Counting to 10",
                "type": "quiz",
                "question": "What number comes after [bold yellow]7[/bold yellow]?",
                "lesson": "Counting order: 1, 2, 3, 4, 5, 6, 7, [bold yellow]8[/bold yellow], 9, 10. Each number is one more than the one before.",
                "options": ["6", "9", "8", "10"],
                "answer": "c",
                "hints": ["Count on your fingers from 1 to 7, then keep going!", "7... 8!"],
                "xp": 25,
            },
            {
                "id": "ch_02",
                "title": "Counting Backwards",
                "type": "quiz",
                "question": "What number comes before [bold yellow]5[/bold yellow]?",
                "lesson": "Counting backwards: 10, 9, 8, 7, 6, [bold yellow]5[/bold yellow], 4, 3, 2, 1. One LESS each time.",
                "options": ["6", "3", "4", "7"],
                "answer": "c",
                "hints": ["Count backwards from 10 — 10, 9, 8, 7, 6, 5... what came just before 5?", "5 - 1 = ?"],
                "xp": 25,
            },
            {
                "id": "ch_03",
                "title": "Counting Objects",
                "type": "quiz",
                "question": "How many stars? ★ ★ ★ ★ ★ ★",
                "lesson": "To count objects, point to each one and say its number. Don't count the same one twice!",
                "options": ["5", "7", "6", "8"],
                "answer": "c",
                "hints": ["Point to each star and count out loud!", "1, 2, 3, 4, 5, 6 — how many was that?"],
                "xp": 25,
            },
            {
                "id": "ch_04",
                "title": "Tens and Ones",
                "type": "quiz",
                "question": "The number [bold yellow]23[/bold yellow] has how many tens?",
                "lesson": "[bold yellow]23[/bold yellow] = 2 tens and 3 ones. The first digit tells you how many groups of ten!",
                "options": ["3", "2", "5", "1"],
                "answer": "b",
                "hints": ["In 23, the 2 is in the tens place and the 3 is in the ones place!", "2 tens = 20"],
                "xp": 30,
            },
            {
                "id": "ch_05",
                "title": "Bigger or Smaller?",
                "type": "quiz",
                "question": "Which number is bigger: [bold yellow]47[/bold yellow] or [bold yellow]74[/bold yellow]?",
                "lesson": "To compare numbers, look at the tens digit first. 7 tens (74) is more than 4 tens (47), so [bold yellow]74[/bold yellow] is bigger.",
                "options": ["47", "74", "They're the same", "Can't tell"],
                "answer": "b",
                "hints": ["Look at the first digit — which is bigger, 4 or 7?", "74 has 7 tens. 47 has only 4 tens!"],
                "xp": 30,
            },
            {
                "id": "ch_06",
                "title": "Skip Counting by 2s",
                "type": "quiz",
                "question": "Count by 2s: 2, 4, 6, [bold yellow]__[/bold yellow], 10",
                "lesson": "Skip counting by 2s: 2, 4, 6, [bold yellow]8[/bold yellow], 10. You're counting every other number!",
                "options": ["7", "9", "8", "11"],
                "answer": "c",
                "hints": ["2, 4, 6... add 2 more!", "6 + 2 = ?"],
                "xp": 30,
            },
            {
                "id": "ch_07",
                "title": "Skip Counting by 5s",
                "type": "quiz",
                "question": "Count by 5s: 5, 10, 15, [bold yellow]__[/bold yellow], 25",
                "lesson": "Skip counting by 5s: 5, 10, 15, [bold yellow]20[/bold yellow], 25. Great for counting nickels!",
                "options": ["16", "21", "18", "20"],
                "answer": "d",
                "hints": ["15 + 5 = ?", "Count on your fingers by 5s!"],
                "xp": 30,
            },
            {
                "id": "ch_boss",
                "title": "Count to 100",
                "type": "quiz",
                "question": "If you count by 10s: 10, 20, 30, 40, 50, 60, 70, 80, 90, [bold yellow]__[/bold yellow]",
                "lesson": "Counting by 10s all the way to [bold yellow]100[/bold yellow]! Each step you add 10 more.",
                "options": ["95", "99", "100", "110"],
                "answer": "c",
                "hints": ["90 + 10 = ?", "One more group of ten after 90 is 100!"],
                "xp": 60,
                "is_boss": True,
            },
        ],
    },

    "addition_meadow": {
        "id": "addition_meadow",
        "name": "The Addition Meadow",
        "description": "Learn to add numbers together",
        "level_required": 2,
        "challenges": [
            {
                "id": "am_01",
                "title": "Adding Small Numbers",
                "type": "fill_blank",
                "question": "[bold white]3 + 4 = ?[/bold white]",
                "lesson": "To add 3 + 4, start at 3 and count up 4 more: 4, 5, 6, [bold yellow]7[/bold yellow].",
                "answer": "7",
                "hints": ["Hold up 3 fingers, then count up 4 more!", "3... 4, 5, 6, 7. Seven!"],
                "xp": 30,
            },
            {
                "id": "am_02",
                "title": "Adding to 10",
                "type": "fill_blank",
                "question": "[bold white]6 + 4 = ?[/bold white]",
                "lesson": "6 + 4 = [bold yellow]10[/bold yellow]. These are called 'number pairs that make 10' — they're useful to memorize!",
                "answer": "10",
                "hints": ["6 + 4... count up from 6: 7, 8, 9, 10!", "Number pairs: 6 and 4 make 10."],
                "xp": 30,
            },
            {
                "id": "am_03",
                "title": "Word Problem",
                "type": "quiz",
                "question": "Nell had [bold yellow]3[/bold yellow] apples. Puck brought [bold yellow]5[/bold yellow] more. How many apples does Nell have now?",
                "lesson": "When we [bold white]add[/bold white], we're finding the total. 3 apples + 5 apples = 8 apples.",
                "options": ["7", "8", "9", "6"],
                "answer": "b",
                "hints": ["Start with 3 and count up 5 more: 4, 5, 6, 7, 8!", "3 + 5 = ?"],
                "xp": 35,
            },
            {
                "id": "am_04",
                "title": "Adding Bigger Numbers",
                "type": "fill_blank",
                "question": "[bold white]12 + 5 = ?[/bold white]",
                "lesson": "12 + 5: start at 12 and count up 5: 13, 14, 15, 16, [bold yellow]17[/bold yellow].",
                "answer": "17",
                "hints": ["Start at 12, count up 5 more!", "12... 13, 14, 15, 16, 17"],
                "xp": 35,
            },
            {
                "id": "am_05",
                "title": "Adding Tens",
                "type": "fill_blank",
                "question": "[bold white]20 + 30 = ?[/bold white]",
                "lesson": "2 tens + 3 tens = 5 tens = [bold yellow]50[/bold yellow]. Adding tens is like adding the regular numbers, but with a zero!",
                "answer": "50",
                "hints": ["2 + 3 = 5, so 20 + 30 = 50!", "Think of it as 2 tens + 3 tens"],
                "xp": 40,
            },
            {
                "id": "am_boss",
                "title": "Two-Digit Addition",
                "type": "fill_blank",
                "question": "[bold white]24 + 13 = ?[/bold white]",
                "lesson": "Add the ones first: 4 + 3 = 7. Then add the tens: 20 + 10 = 30. Together: 30 + 7 = [bold yellow]37[/bold yellow].",
                "answer": "37",
                "hints": ["Add the ones (4+3), then add the tens (20+10), then combine!", "4+3=7, 20+10=30, 30+7=37"],
                "xp": 70,
                "is_boss": True,
            },
        ],
    },

    "subtraction_valley": {
        "id": "subtraction_valley",
        "name": "The Subtraction Valley",
        "description": "Learn to take numbers away",
        "level_required": 3,
        "challenges": [
            {
                "id": "sv_01",
                "title": "Taking Away",
                "type": "fill_blank",
                "question": "[bold white]8 - 3 = ?[/bold white]",
                "lesson": "Subtraction means taking away. Start at 8 and count back 3: 7, 6, [bold yellow]5[/bold yellow].",
                "answer": "5",
                "hints": ["Hold up 8 fingers, fold down 3 — how many are left?", "8... 7, 6, 5. Five!"],
                "xp": 30,
            },
            {
                "id": "sv_02",
                "title": "Subtraction Word Problem",
                "type": "quiz",
                "question": "Nell had [bold yellow]10[/bold yellow] cookies. She ate [bold yellow]4[/bold yellow]. How many are left?",
                "lesson": "10 - 4 = 6. Subtraction tells us what's left over.",
                "options": ["5", "7", "6", "8"],
                "answer": "c",
                "hints": ["10 take away 4... count back from 10: 9, 8, 7, 6!", "10 - 4 = ?"],
                "xp": 35,
            },
            {
                "id": "sv_03",
                "title": "Subtraction from 10",
                "type": "fill_blank",
                "question": "[bold white]10 - 7 = ?[/bold white]",
                "lesson": "10 - 7 = [bold yellow]3[/bold yellow]. These are the same pairs as addition! If 7 + 3 = 10, then 10 - 7 = 3.",
                "answer": "3",
                "hints": ["If 7 + 3 = 10, then 10 - 7 = ?", "Count back from 10: 9, 8, 7...that's 3 steps!"],
                "xp": 35,
            },
            {
                "id": "sv_04",
                "title": "Missing Numbers",
                "type": "fill_blank",
                "question": "What number goes in the blank?\n[bold white]9 - __ = 5[/bold white]",
                "lesson": "To find the missing number, ask: what do I take from 9 to get 5? Count from 5 up to 9: 6, 7, 8, 9 — that's [bold yellow]4[/bold yellow] steps.",
                "answer": "4",
                "hints": ["Count from 5 up to 9 — how many steps is that?", "5... 6, 7, 8, 9. That's 4 steps, so 9 - 4 = 5!"],
                "xp": 40,
            },
            {
                "id": "sv_boss",
                "title": "Bigger Subtraction",
                "type": "fill_blank",
                "question": "[bold white]25 - 12 = ?[/bold white]",
                "lesson": "Subtract the ones: 5 - 2 = 3. Subtract the tens: 20 - 10 = 10. Together: 10 + 3 = [bold yellow]13[/bold yellow].",
                "answer": "13",
                "hints": ["Subtract the ones (5-2=3), then the tens (20-10=10), then add!", "5-2=3, 20-10=10, 10+3=13"],
                "xp": 70,
                "is_boss": True,
            },
        ],
    },

    "shape_forest": {
        "id": "shape_forest",
        "name": "The Shape Forest",
        "description": "Identify and understand 2D shapes",
        "level_required": 4,
        "challenges": [
            {
                "id": "sf_01",
                "title": "The Circle",
                "type": "quiz",
                "question": "How many sides does a [bold yellow]circle[/bold yellow] have?",
                "lesson": "A circle has [bold yellow]0[/bold yellow] sides and [bold yellow]0[/bold yellow] corners — it's one continuous curved line. Coins, wheels, and clocks are circles!",
                "options": ["1", "0", "2", "4"],
                "answer": "b",
                "hints": ["Run your finger around a circle — can you find a corner or a straight side?", "A circle is all curve, no straight edges!"],
                "xp": 30,
            },
            {
                "id": "sf_02",
                "title": "The Triangle",
                "type": "quiz",
                "question": "How many sides does a [bold yellow]triangle[/bold yellow] have?",
                "lesson": "A triangle has [bold yellow]3[/bold yellow] sides and [bold yellow]3[/bold yellow] corners. 'Tri' means three — like tricycle (three wheels)!",
                "options": ["2", "4", "3", "5"],
                "answer": "c",
                "hints": ["'Tri' means three — in triangle, tricycle, tripod!", "Count the sides: 1, 2, 3"],
                "xp": 30,
            },
            {
                "id": "sf_03",
                "title": "The Square",
                "type": "quiz",
                "question": "What makes a [bold yellow]square[/bold yellow] special compared to a rectangle?",
                "lesson": "A square has [bold yellow]4[/bold yellow] equal sides and [bold yellow]4[/bold yellow] right angle corners. All four sides are the SAME length!",
                "options": ["It has more sides", "All 4 sides are equal", "It has no corners", "It has 3 sides"],
                "answer": "b",
                "hints": ["A square and rectangle both have 4 sides — but what's different?", "A square's sides are all the same length!"],
                "xp": 35,
            },
            {
                "id": "sf_04",
                "title": "The Rectangle",
                "type": "quiz",
                "question": "A door is shaped like a [bold yellow]rectangle[/bold yellow]. How many sides does it have?",
                "lesson": "A rectangle has [bold yellow]4[/bold yellow] sides and [bold yellow]4[/bold yellow] corners. Two sides are long, two sides are short (unless it's a square, which is a special rectangle!).",
                "options": ["3", "5", "4", "6"],
                "answer": "c",
                "hints": ["Look at a door or a book — count the edges!", "Rectangles have 4 sides"],
                "xp": 35,
            },
            {
                "id": "sf_05",
                "title": "The Pentagon and Hexagon",
                "type": "quiz",
                "question": "A [bold yellow]hexagon[/bold yellow] looks like a honeycomb cell. How many sides does it have?",
                "lesson": "'Hex' means six! A [bold yellow]hexagon[/bold yellow] has 6 sides. Honeybees build their homes in hexagons!",
                "options": ["5", "7", "8", "6"],
                "answer": "d",
                "hints": ["'Hex' means six — like hexapod (6 legs)!", "Count the sides of a honeycomb shape"],
                "xp": 40,
            },
            {
                "id": "sf_boss",
                "title": "Shape Challenge",
                "type": "quiz",
                "question": "Which shape has the MOST sides: triangle, pentagon, rectangle, or octagon?",
                "lesson": "Triangle=3, Rectangle=4, Pentagon=5, [bold yellow]Octagon=8[/bold yellow]. 'Oct' means eight — like October (was the 8th month in old calendars)!",
                "options": ["Triangle", "Pentagon", "Rectangle", "Octagon"],
                "answer": "d",
                "hints": ["Count each one: triangle=3, rectangle=4, pentagon=5, octagon=?", "'Oct' means 8 — octopus has 8 arms!"],
                "xp": 80,
                "is_boss": True,
            },
        ],
    },

    "time_tower": {
        "id": "time_tower",
        "name": "The Time Tower",
        "description": "Read a clock and understand time",
        "level_required": 5,
        "challenges": [
            {
                "id": "tt_01",
                "title": "Parts of a Clock",
                "type": "quiz",
                "question": "On a clock, the [bold yellow]short hand[/bold yellow] points to the...",
                "lesson": "The short hand shows the [bold yellow]hours[/bold yellow]. The long hand shows the [bold yellow]minutes[/bold yellow]. Short = hours, long = minutes!",
                "options": ["seconds", "minutes", "hours", "days"],
                "answer": "c",
                "hints": ["Short hand = short word = HOUR", "The SHORT hand points to the HOUR"],
                "xp": 35,
            },
            {
                "id": "tt_02",
                "title": "Reading O'Clock",
                "type": "quiz",
                "question": "The short hand points to [bold yellow]3[/bold yellow], and the long hand points straight up to [bold yellow]12[/bold yellow]. What time is it?",
                "lesson": "When the long hand points to 12, it's exactly the hour — called 'o'clock'. Short hand on 3 = [bold yellow]3 o'clock[/bold yellow]!",
                "options": ["12:03", "3:00", "3:12", "12:30"],
                "answer": "b",
                "hints": ["Long hand on 12 = o'clock. Short hand on 3 = what hour?", "3 o'clock = 3:00"],
                "xp": 40,
            },
            {
                "id": "tt_03",
                "title": "Half Past",
                "type": "quiz",
                "question": "When the long hand points to [bold yellow]6[/bold yellow], it's 'half past'. If the short hand is between 7 and 8, it's...",
                "lesson": "Long hand on 6 = 30 minutes = half past the hour. Short hand between 7 and 8 = [bold yellow]7:30[/bold yellow].",
                "options": ["6:07", "7:06", "7:30", "6:30"],
                "answer": "c",
                "hints": ["Long hand on 6 = 30 minutes have passed", "Short hand shows which hour we're in — between 7 and 8 means 7:30"],
                "xp": 45,
            },
            {
                "id": "tt_04",
                "title": "Days of the Week",
                "type": "quiz",
                "question": "How many days are in a week?",
                "lesson": "A week has [bold yellow]7[/bold yellow] days: Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday. Mon-Fri are school days for most kids!",
                "options": ["5", "6", "8", "7"],
                "answer": "d",
                "hints": ["Count them: Sun, Mon, Tue, Wed, Thu, Fri, Sat", "7 days in a week — lucky 7!"],
                "xp": 30,
            },
            {
                "id": "tt_05",
                "title": "Months of the Year",
                "type": "quiz",
                "question": "How many months are in a year?",
                "lesson": "A year has [bold yellow]12[/bold yellow] months. January through December. Some have 30 days, some 31, and February is special with 28 (or 29 on leap years)!",
                "options": ["10", "12", "11", "13"],
                "answer": "b",
                "hints": ["Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec — count them!", "12 months in a year"],
                "xp": 35,
            },
            {
                "id": "tt_boss",
                "title": "Time Goes By",
                "type": "quiz",
                "question": "School starts at [bold yellow]8:00[/bold yellow] and ends at [bold yellow]3:00[/bold yellow]. How many hours is the school day?",
                "lesson": "From 8:00 to 3:00 — count the hours: 9, 10, 11, 12, 1, 2, 3. That's [bold yellow]7 hours[/bold yellow]!",
                "options": ["5 hours", "6 hours", "8 hours", "7 hours"],
                "answer": "d",
                "hints": ["Count from 8 to 3: 8→9→10→11→12→1→2→3 — how many steps?", "8, 9, 10, 11, 12, 1, 2, 3 — that's 7 jumps!"],
                "xp": 90,
                "is_boss": True,
            },
        ],
    },
}
