"""
zones.py — Logic skill pack — The Puzzle Palace
"""

ZONE_ORDER = ['pattern_recognition', 'number_sequences', 'true_or_false_logic', 'if_then_thinking', 'brain_teasers']

ZONES = {
    "pattern_recognition": {
        "id": "pattern_recognition",
        "name": 'The Pattern Workshop',
        "description": 'Spot shapes, colors, and repeating patterns all around you',
        "level_required": 1,
        "challenges": [
            {
                "id": 'pr_shape_repeat',
                "question": 'What comes next? Circle, Square, Circle, Square, Circle, ___',
                "type": 'quiz',
                "options": ['Triangle', 'Square', 'Circle', 'Star'],
                "answer": 'b',
                "lesson": "This is an AB repeating pattern. The two shapes take turns: Circle, Square, Circle, Square. After Circle, it is always Square's turn!",
                "xp": 20,
            },
            {
                "id": 'pr_color_pattern',
                "question": 'Red, Blue, Green, Red, Blue, Green, Red, ___. What color comes next?',
                "type": 'quiz',
                "options": ['Red', 'Green', 'Blue', 'Yellow'],
                "answer": 'c',
                "lesson": 'This is an ABC pattern that repeats every three items. After Red the cycle starts over: Blue comes next, then Green, then Red again.',
                "xp": 20,
            },
            {
                "id": 'pr_odd_one_out',
                "question": 'Which one does NOT belong? Apple, Banana, Carrot, Grape',
                "type": 'quiz',
                "options": ['Apple', 'Banana', 'Carrot', 'Grape'],
                "answer": 'c',
                "lesson": 'Apple, Banana, and Grape are all fruits. Carrot is a vegetable, so it does not belong in a group of fruits. Finding the odd one out means looking at what the others have in common.',
                "xp": 20,
            },
            {
                "id": 'pr_mirror_image',
                "question": 'If you fold a butterfly drawing right down the middle, the left wing matches the right wing. What is that called?',
                "type": 'quiz',
                "options": ['Rotation', 'Symmetry', 'Repetition', 'Translation'],
                "answer": 'b',
                "lesson": 'Symmetry means one side is a mirror image of the other. Butterflies, leaves, and even your own face are nearly symmetrical!',
                "xp": 25,
            },
            {
                "id": 'pr_growing_pattern',
                "question": 'How many dots come next? 1 dot, 3 dots, 5 dots, 7 dots, ___',
                "type": 'quiz',
                "options": ['8', '9', '10', '11'],
                "answer": 'b',
                "lesson": 'Each step adds 2 more dots than before: 1, 3, 5, 7... so the next number is 7 + 2 = 9. These are called odd numbers, and they form a pattern that grows by 2 every time.',
                "xp": 25,
            },
            {
                "id": 'pr_shape_series',
                "question": 'Triangle, Triangle, Square, Triangle, Triangle, Square, Triangle, Triangle, ___',
                "type": 'quiz',
                "options": ['Triangle', 'Circle', 'Square', 'Star'],
                "answer": 'c',
                "lesson": "The pattern repeats in groups of three: Triangle, Triangle, Square. After two Triangles, it is always Square's turn. Recognizing the group size is the key!",
                "xp": 25,
            },
            {
                "id": 'pr_letter_pattern',
                "question": 'What letter comes next? A, C, E, G, ___',
                "type": 'text',
                "options": [],
                "answer": 'I',
                "lesson": 'We are skipping every other letter in the alphabet: A (skip B), C (skip D), E (skip F), G (skip H), I. The pattern adds 2 letters each time.',
                "xp": 30,
            },
            {
                "id": 'pr_complex_pattern',
                "question": 'Look at this pattern: 1, A, 2, B, 3, C, 4, ___. What comes next?',
                "type": 'text',
                "options": [],
                "answer": 'D',
                "lesson": 'Two patterns are woven together! The numbers count up (1, 2, 3, 4...) and the letters go in alphabet order (A, B, C, D...). They take turns. After the number 4, the next letter is D.',
                "xp": 35,
            },
        ],
    },
    "number_sequences": {
        "id": "number_sequences",
        "name": 'The Sequence Staircase',
        "description": 'Climb the staircase by cracking number codes and sequences',
        "level_required": 3,
        "challenges": [
            {
                "id": 'ns_count_by_three',
                "question": 'What comes next? 3, 6, 9, 12, ___',
                "type": 'quiz',
                "options": ['13', '14', '15', '16'],
                "answer": 'c',
                "lesson": 'This is counting by threes. Each number is 3 more than the one before. You can use this to count groups of things quickly: 3 cookies per plate means 3, 6, 9, 12, 15...',
                "xp": 20,
            },
            {
                "id": 'ns_doubles',
                "question": 'Each number doubles! 2, 4, 8, 16, ___',
                "type": 'quiz',
                "options": ['24', '32', '18', '20'],
                "answer": 'b',
                "lesson": 'Doubling means multiplying by 2. 16 x 2 = 32. Doubling grows very fast -- if you folded a piece of paper in half 42 times, it would reach the Moon!',
                "xp": 25,
            },
            {
                "id": 'ns_subtract_pattern',
                "question": 'What comes next? 50, 45, 40, 35, ___',
                "type": 'quiz',
                "options": ['25', '32', '30', '28'],
                "answer": 'c',
                "lesson": 'This sequence goes DOWN by 5 each time. Patterns can shrink as well as grow! 35 minus 5 equals 30.',
                "xp": 25,
            },
            {
                "id": 'ns_add_increasing',
                "question": 'Each time we add one more: 1, 2, 4, 7, 11, ___. What comes next?',
                "type": 'quiz',
                "options": ['14', '15', '16', '17'],
                "answer": 'c',
                "lesson": 'The gap between numbers keeps growing: +1, +2, +3, +4... so the next gap is +5. 11 + 5 = 16. When the rule itself changes each step, look at the differences!',
                "xp": 30,
            },
            {
                "id": 'ns_square_numbers',
                "question": '1, 4, 9, 16, 25, ___. What comes next?',
                "type": 'quiz',
                "options": ['30', '35', '36', '49'],
                "answer": 'c',
                "lesson": "These are square numbers! 1x1=1, 2x2=4, 3x3=9, 4x4=16, 5x5=25, 6x6=36. They are called 'square' because you can arrange that many dots into a perfect square shape.",
                "xp": 30,
            },
            {
                "id": 'ns_fibonacci_easy',
                "question": 'Each number is the sum of the two before it: 1, 1, 2, 3, 5, 8, ___',
                "type": 'text',
                "options": [],
                "answer": '13',
                "lesson": 'This is the Fibonacci sequence! 5 + 8 = 13. This pattern shows up in sunflower spirals, pinecone bumps, and seashell curves. Nature loves this sequence!',
                "xp": 35,
            },
            {
                "id": 'ns_alternating',
                "question": 'What comes next? 2, 5, 3, 6, 4, 7, 5, ___',
                "type": 'text',
                "options": [],
                "answer": '8',
                "lesson": 'There are two sequences woven together! The odd positions go 2, 3, 4, 5 (adding 1) and the even positions go 5, 6, 7, 8 (also adding 1). The next even-position number is 8.',
                "xp": 35,
            },
            {
                "id": 'ns_times_table_gap',
                "question": 'Fill in the missing number: 7, 14, ___, 28, 35',
                "type": 'text',
                "options": [],
                "answer": '21',
                "lesson": 'This is the 7 times table! 7, 14, 21, 28, 35. Each number is 7 more than the last. Recognizing times tables hidden in sequences is a powerful math skill.',
                "xp": 30,
            },
        ],
    },
    "true_or_false_logic": {
        "id": "true_or_false_logic",
        "name": 'The Truth Tower',
        "description": 'Test statements and discover what is true, false, or tricky',
        "level_required": 5,
        "challenges": [
            {
                "id": 'tf_basic_true',
                "question": 'True or False: All dogs are animals.',
                "type": 'quiz',
                "options": ['True', 'False', 'Sometimes', 'It depends'],
                "answer": 'a',
                "lesson": "This is TRUE. Every single dog is an animal. When we say 'all,' we mean every single one with no exceptions. If even one dog were not an animal, the statement would be false.",
                "xp": 20,
            },
            {
                "id": 'tf_basic_false',
                "question": 'True or False: All birds can fly.',
                "type": 'quiz',
                "options": ['True', 'False', 'Only big birds', 'Only small birds'],
                "answer": 'b',
                "lesson": "This is FALSE! Penguins, ostriches, and kiwis are all birds that cannot fly. When a statement says 'all,' you only need ONE exception to prove it false.",
                "xp": 20,
            },
            {
                "id": 'tf_tricky_some',
                "question": 'True or False: Some fish live in fresh water.',
                "type": 'quiz',
                "options": ['True', 'False', 'All fish do', 'No fish do'],
                "answer": 'a',
                "lesson": "TRUE! The word 'some' is important. It means 'at least one.' Goldfish and trout live in fresh water, so 'some fish live in fresh water' is true, even though other fish live in salt water.",
                "xp": 25,
            },
            {
                "id": 'tf_negation',
                "question": "If 'The sky is blue' is TRUE, what about 'The sky is NOT blue'?",
                "type": 'quiz',
                "options": ['Also true', 'False', 'Sometimes true', 'We cannot tell'],
                "answer": 'b',
                "lesson": "When a statement is TRUE, its opposite (the negation) is FALSE. Adding 'NOT' flips the truth value. True becomes false, and false becomes true. This is the foundation of logic!",
                "xp": 25,
            },
            {
                "id": 'tf_and_logic',
                "question": "Is this statement true? 'Cats have fur AND the Moon is made of cheese.'",
                "type": 'quiz',
                "options": ['True', 'False', 'Half true', 'Depends on the cat'],
                "answer": 'b',
                "lesson": 'With AND, BOTH parts must be true for the whole thing to be true. Cats do have fur (true!), but the Moon is NOT made of cheese (false!). True AND False = False.',
                "xp": 30,
            },
            {
                "id": 'tf_or_logic',
                "question": "True or False: 'Fish live in water OR fish live on the Moon.'",
                "type": 'quiz',
                "options": ['True', 'False', 'Both parts are true', 'Neither part is true'],
                "answer": 'a',
                "lesson": 'With OR, only ONE part needs to be true. Fish DO live in water (true!), so the whole statement is true even though fish do NOT live on the Moon. True OR False = True.',
                "xp": 30,
            },
            {
                "id": 'tf_always_never',
                "question": "Which word makes a statement harder to prove true: 'always' or 'sometimes'?",
                "type": 'text',
                "options": [],
                "answer": 'always',
                "lesson": "'Always' means every single time with zero exceptions, so you need to check every case. 'Sometimes' only needs one example to be true. That is why scientists are careful with the word 'always'!",
                "xp": 30,
            },
            {
                "id": 'tf_contrapositive',
                "question": "If 'All apples are fruits' is true, which of these must also be true?",
                "type": 'quiz',
                "options": ['All fruits are apples', 'If something is not a fruit, it is not an apple', 'Some apples are not fruits', 'No fruits are apples'],
                "answer": 'b',
                "lesson": 'This is called the contrapositive. If ALL apples are fruits, then anything that is NOT a fruit cannot be an apple. But careful: all fruits are NOT necessarily apples -- oranges are fruits too!',
                "xp": 35,
            },
        ],
    },
    "if_then_thinking": {
        "id": "if_then_thinking",
        "name": 'The Cause & Effect Lab',
        "description": 'Explore what happens when one thing leads to another',
        "level_required": 8,
        "challenges": [
            {
                "id": 'it_basic_cause',
                "question": 'IF it rains, THEN the ground gets wet. It rained today. What do we know?',
                "type": 'quiz',
                "options": ['The ground is wet', 'The ground is dry', 'It might be wet', 'We cannot tell'],
                "answer": 'a',
                "lesson": 'This is a simple if-then rule. The IF part happened (it rained), so the THEN part must happen (the ground gets wet). When the condition is met, the result follows!',
                "xp": 20,
            },
            {
                "id": 'it_condition_not_met',
                "question": 'IF you press the button, THEN the light turns on. You did NOT press the button. Is the light on?',
                "type": 'quiz',
                "options": ['Yes, the light is on', 'No, the light is off', 'We cannot be sure', 'The light is broken'],
                "answer": 'c',
                "lesson": 'Tricky! We only know what happens IF you press the button. Maybe the light is on for a different reason (someone else pressed it, or it has a timer). When the IF part does not happen, we cannot be sure about the THEN part.',
                "xp": 30,
            },
            {
                "id": 'it_chain_reaction',
                "question": 'IF it snows, THEN school is canceled. IF school is canceled, THEN you play outside. It snowed! What happens?',
                "type": 'quiz',
                "options": ['You go to school', 'You play outside', 'Nothing happens', 'It stops snowing'],
                "answer": 'b',
                "lesson": 'This is a chain of if-then rules! Snow leads to no school, and no school leads to playing outside. Each step triggers the next, like a row of dominoes falling.',
                "xp": 25,
            },
            {
                "id": 'it_reverse_error',
                "question": 'IF an animal is a dog, THEN it has four legs. Fluffy has four legs. Is Fluffy definitely a dog?',
                "type": 'quiz',
                "options": ['Yes, Fluffy must be a dog', 'No, Fluffy could be another animal', 'Only if Fluffy barks', 'Yes, all four-legged animals are dogs'],
                "answer": 'b',
                "lesson": "Be careful! Just because dogs have four legs does not mean everything with four legs is a dog. Cats, horses, and tables have four legs too! This mistake is called 'affirming the consequent.'",
                "xp": 30,
            },
            {
                "id": 'it_everyday_rule',
                "question": 'IF you eat your vegetables, THEN you get dessert. You did not get dessert. What do we know?',
                "type": 'quiz',
                "options": ['You ate your vegetables', 'You did not eat your vegetables', 'The dessert was gone', 'We cannot tell'],
                "answer": 'b',
                "lesson": "If the THEN part did not happen (no dessert), the IF part could not have happened either (you did not eat vegetables). This is called 'modus tollens' -- working backwards from the result!",
                "xp": 35,
            },
            {
                "id": 'it_two_conditions',
                "question": 'IF it is Saturday AND sunny, THEN we go to the park. Today is Saturday but it is raining. Do we go to the park?',
                "type": 'quiz',
                "options": ['Yes', 'No', 'Only in the morning', 'We go somewhere else'],
                "answer": 'b',
                "lesson": 'When a rule has AND, ALL conditions must be true. It is Saturday (yes!) but NOT sunny (no!). Since both must be true and one is false, we do not go to the park.',
                "xp": 30,
            },
            {
                "id": 'it_predict_outcome',
                "question": 'IF you study hard, THEN you do well on the test. IF you do well on the test, THEN you feel proud. You studied hard. How do you feel?',
                "type": 'text',
                "options": [],
                "answer": 'proud',
                "lesson": 'Following the chain: studying leads to doing well, and doing well leads to feeling proud. If-then chains help us predict the future by following causes to their effects, step by step.',
                "xp": 30,
            },
            {
                "id": 'it_robot_commands',
                "question": 'A robot follows these rules: IF it sees red, THEN stop. IF it sees green, THEN go. IF it sees yellow, THEN slow down. The robot sees yellow then green. What does it do?',
                "type": 'text',
                "options": [],
                "answer": 'slow down then go',
                "lesson": 'The robot follows each rule in order. First it sees yellow, so it slows down. Then it sees green, so it goes. Computers and robots follow if-then rules just like this -- that is how programs work!',
                "xp": 35,
            },
        ],
    },
    "brain_teasers": {
        "id": "brain_teasers",
        "name": 'The Riddle Vault',
        "description": 'Put all your logic skills together to solve tricky brain teasers',
        "level_required": 10,
        "challenges": [
            {
                "id": 'bt_coin_flip',
                "question": 'I have two coins that add up to 30 cents. One of them is NOT a nickel. What are the two coins?',
                "type": 'quiz',
                "options": ['Two dimes', 'A quarter and a nickel', 'A dime and two nickels', 'A penny and a quarter'],
                "answer": 'b',
                "lesson": "The trick is the word 'one of them.' ONE coin is not a nickel -- that is the quarter! But the OTHER coin IS a nickel. The puzzle never said NEITHER coin is a nickel. Read carefully!",
                "xp": 30,
            },
            {
                "id": 'bt_farmer_crossing',
                "question": 'A farmer has a fox, a chicken, and corn. He must cross a river but can only carry one at a time. The fox will eat the chicken if left alone, and the chicken will eat the corn. What should he take first?',
                "type": 'quiz',
                "options": ['The fox', 'The corn', 'The chicken', 'It is impossible'],
                "answer": 'c',
                "lesson": 'Take the chicken first! The fox will not eat the corn, so they are safe together. Then come back, take the fox across, but bring the chicken BACK. Then take the corn across, and finally the chicken again.',
                "xp": 35,
            },
            {
                "id": 'bt_ages_riddle',
                "question": 'Sam is 4 years old. His big sister is twice his age. When Sam is 10, how old will his sister be?',
                "type": 'quiz',
                "options": ['20', '16', '14', '12'],
                "answer": 'c',
                "lesson": 'Right now Sam is 4 and his sister is 8 (twice 4). The age GAP between them is always 4 years. When Sam is 10, his sister will be 10 + 4 = 14. The gap stays the same even though the ratio changes!',
                "xp": 30,
            },
            {
                "id": 'bt_socks_drawer',
                "question": 'You have a drawer with 10 red socks and 10 blue socks, all mixed up. It is dark and you cannot see. What is the fewest socks you must grab to be SURE you have a matching pair?',
                "type": 'quiz',
                "options": ['2', '3', '10', '11'],
                "answer": 'b',
                "lesson": 'You only need 3 socks! The first two might be different colors (one red, one blue). But the third sock MUST match one of them -- there are only two colors. This is the pigeonhole principle!',
                "xp": 35,
            },
            {
                "id": 'bt_lily_pad',
                "question": 'A lily pad doubles in size every day. On day 20 it covers the whole pond. On what day did it cover HALF the pond?',
                "type": 'quiz',
                "options": ['Day 10', 'Day 15', 'Day 18', 'Day 19'],
                "answer": 'd',
                "lesson": 'Since it DOUBLES each day, on day 19 it was half the size it is on day 20. Many people guess day 10 because half of 20 is 10, but doubling does not work that way. Exponential growth is surprising!',
                "xp": 35,
            },
            {
                "id": 'bt_birthday_candles',
                "question": 'How many times does the digit 1 appear when you write all the numbers from 1 to 20?',
                "type": 'text',
                "options": [],
                "answer": '12',
                "lesson": "Let's count! The 1 appears in: 1, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19. That is 1 (once) + 10 (once) + 11 (twice!) + 12 through 19 (once each = 8). Total: 1 + 1 + 2 + 8 = 12.",
                "xp": 35,
            },
            {
                "id": 'bt_handshake',
                "question": 'Four friends meet and every person shakes hands with every other person exactly once. How many handshakes happen in total?',
                "type": 'text',
                "options": [],
                "answer": '6',
                "lesson": 'Person 1 shakes with 3 others. Person 2 shakes with 2 remaining. Person 3 shakes with 1 remaining. Person 4 has already shaken with everyone. 3 + 2 + 1 = 6. The formula is n(n-1)/2!',
                "xp": 35,
            },
            {
                "id": 'bt_weighing_puzzle',
                "question": 'You have 8 identical-looking balls. One is slightly heavier. Using a balance scale, what is the fewest number of weighings needed to ALWAYS find the heavy one?',
                "type": 'quiz',
                "options": ['1', '2', '3', '4'],
                "answer": 'b',
                "lesson": 'Split into groups of 3, 3, and 2. Weigh the two groups of 3. If they balance, the heavy ball is in the group of 2 (one more weighing). If they do not, take the heavier group of 3 and weigh 1 vs 1. Two weighings always works!',
                "xp": 40,
            },
        ],
    },
}
