"""
zones.py — Letter zones and challenges for the Letters skill pack.

Challenge types used here:
  - "quiz" : multiple choice — shows options A/B/C/D, player types letter
  - "fill_blank" : player types a short answer

All designed for a 7-year-old learning to read.
"""

ZONE_ORDER = [
    "letter_garden",
    "vowel_pond",
    "blend_bridge",
    "word_workshop",
    "sentence_city",
]

ZONES = {
    "letter_garden": {
        "id": "letter_garden",
        "name": "The Letter Garden",
        "description": "Learn the sounds of the alphabet",
        "level_required": 1,
        "challenges": [
            {
                "id": "lg_01",
                "title": "The Letter A",
                "type": "quiz",
                "question": "What sound does the letter [bold yellow]A[/bold yellow] make at the start of the word [bold white]apple[/bold white]?",
                "lesson": "A says 'ah' — like when a doctor says 'say ahh!' Think: [bold yellow]A[/bold yellow] for [bold white]apple[/bold white].",
                "options": ["'ay' (like in cake)", "'ah' (like in apple)", "'ee' (like in feel)", "'oh' (like in open)"],
                "answer": "b",
                "hints": ["Think of the word APPLE. What's the very first sound?", "Try saying 'apple' really slowly: aaa-pple"],
                "xp": 30,
            },
            {
                "id": "lg_02",
                "title": "The Letter B",
                "type": "quiz",
                "question": "What sound does [bold yellow]B[/bold yellow] make? Which word starts with a B sound?",
                "lesson": "B says 'buh' — a soft popping sound with your lips. [bold yellow]B[/bold yellow] for [bold white]ball[/bold white], [bold white]boat[/bold white], [bold white]bear[/bold white].",
                "options": ["Dog", "Ball", "Cat", "Fish"],
                "answer": "b",
                "hints": ["Close your lips and make a small pop — that's the B sound!", "Ball starts with B"],
                "xp": 30,
            },
            {
                "id": "lg_03",
                "title": "The Letter C",
                "type": "quiz",
                "question": "The letter [bold yellow]C[/bold yellow] can say 'kuh'. Which of these starts with that sound?",
                "lesson": "[bold yellow]C[/bold yellow] usually says 'kuh' like in [bold white]cat[/bold white] or [bold white]cup[/bold white].",
                "options": ["Elephant", "Apple", "Cat", "Uncle"],
                "answer": "c",
                "hints": ["Cat, cake, cup — they all start with the same sound!", "It's the same sound as K!"],
                "xp": 30,
            },
            {
                "id": "lg_04",
                "title": "The Letter D",
                "type": "quiz",
                "question": "What letter makes the first sound in [bold white]dog[/bold white]?",
                "lesson": "[bold yellow]D[/bold yellow] says 'duh'. Your tongue taps the roof of your mouth. [bold white]Dog, door, duck[/bold white] — all start with D!",
                "options": ["B", "G", "D", "P"],
                "answer": "c",
                "hints": ["Say 'dog' slowly. What's the very first sound?", "D-D-Dog — there it is!"],
                "xp": 30,
            },
            {
                "id": "lg_05",
                "title": "Letters F and G",
                "type": "quiz",
                "question": "Which word starts with the letter [bold yellow]F[/bold yellow]?",
                "lesson": "[bold yellow]F[/bold yellow] says 'fff' — your top teeth touch your bottom lip. [bold white]Fish, frog, flower[/bold white] all start with F!",
                "options": ["Goat", "Hat", "Fish", "Ball"],
                "answer": "c",
                "hints": ["Put your top teeth on your bottom lip and blow — that's F!", "Fish starts with F"],
                "xp": 30,
            },
            {
                "id": "lg_06",
                "title": "Letters H and J",
                "type": "quiz",
                "question": "What letter makes the beginning sound in [bold white]jump[/bold white]?",
                "lesson": "[bold yellow]J[/bold yellow] says 'juh' — like [bold white]jump, jelly, jar[/bold white]. It's a bouncy sound!",
                "options": ["H", "J", "G", "Y"],
                "answer": "b",
                "hints": ["Jump! Say it out loud — what's that very first sound?", "J-J-Jump!"],
                "xp": 30,
            },
            {
                "id": "lg_07",
                "title": "Letters K and L",
                "type": "quiz",
                "question": "Which word starts with the [bold yellow]L[/bold yellow] sound?",
                "lesson": "[bold yellow]L[/bold yellow] says 'lll' — your tongue touches behind your top teeth and stays there while air flows around it. [bold white]Lion, lamp, leaf[/bold white] start with L.",
                "options": ["Kite", "Lion", "Mouse", "Nest"],
                "answer": "b",
                "hints": ["L sounds like the start of 'lullaby'", "Say 'lll' — it flows! Lion starts with that sound."],
                "xp": 30,
            },
            {
                "id": "lg_08",
                "title": "Letters M and N",
                "type": "quiz",
                "question": "What letter do you hear at the start of [bold white]moon[/bold white]?",
                "lesson": "[bold yellow]M[/bold yellow] says 'mmm' — close your lips and hum. [bold white]Moon, mouse, milk, mom[/bold white] — all start with M!",
                "options": ["N", "W", "M", "B"],
                "answer": "c",
                "hints": ["Close your mouth and hum. That's the M sound!", "Moon, milk, mom — mmm!"],
                "xp": 30,
            },
            {
                "id": "lg_boss",
                "title": "P, Q, R, S, and T — The Big Five",
                "type": "quiz",
                "question": "Which letter makes the sound at the start of [bold white]star[/bold white]?",
                "lesson": "[bold yellow]S[/bold yellow] says 'sss' — like a snake! [bold white]Sun, star, snake, sock[/bold white] — all start with S.",
                "options": ["T", "P", "S", "R"],
                "answer": "c",
                "hints": ["Hiss like a snake — that's the S sound!", "Star begins with S!"],
                "xp": 60,
                "is_boss": True,
            },
        ],
    },

    "vowel_pond": {
        "id": "vowel_pond",
        "name": "The Vowel Pond",
        "description": "Master the five vowels and their sounds",
        "level_required": 2,
        "challenges": [
            {
                "id": "vp_01",
                "title": "Short A",
                "type": "quiz",
                "question": "Which word has the short [bold yellow]A[/bold yellow] sound (like in [bold white]cat[/bold white])?",
                "lesson": "Short A says 'aaa' — like in [bold white]cat, hat, map, cap[/bold white]. It's quick and flat.",
                "options": ["cake", "cat", "make", "lake"],
                "answer": "b",
                "hints": ["Short A is quick — like 'aaa' in a sneeze!", "Cat: C-aaa-T. That's the short A!"],
                "xp": 35,
            },
            {
                "id": "vp_02",
                "title": "Short E",
                "type": "quiz",
                "question": "Which word uses the short [bold yellow]E[/bold yellow] sound (like in [bold white]bed[/bold white])?",
                "lesson": "Short E says 'ehh' — like in [bold white]bed, red, hen, ten[/bold white].",
                "options": ["tree", "bee", "red", "see"],
                "answer": "c",
                "hints": ["Short E sounds like the middle of the word 'bed'", "Bed, red, hen — ehh!"],
                "xp": 35,
            },
            {
                "id": "vp_03",
                "title": "Short I",
                "type": "quiz",
                "question": "Which word has the short [bold yellow]I[/bold yellow] sound (like in [bold white]pig[/bold white])?",
                "lesson": "Short I says 'ihh' — like in [bold white]pig, big, sit, tip[/bold white]. It's a small, quick sound.",
                "options": ["pie", "bike", "pig", "like"],
                "answer": "c",
                "hints": ["Short I is quick — like the middle of 'sit'", "Pig: P-ihh-G. Short I!"],
                "xp": 35,
            },
            {
                "id": "vp_04",
                "title": "Short O",
                "type": "quiz",
                "question": "Which word uses the short [bold yellow]O[/bold yellow] sound (like in [bold white]hot[/bold white])?",
                "lesson": "Short O says 'ahh' — like in [bold white]hot, dog, pop, top[/bold white]. Your mouth opens wide!",
                "options": ["home", "hot", "hope", "hole"],
                "answer": "b",
                "hints": ["Open your mouth wide — that's the short O!", "Hot: H-ahh-T. Short O!"],
                "xp": 35,
            },
            {
                "id": "vp_05",
                "title": "Short U",
                "type": "quiz",
                "question": "Which word has the short [bold yellow]U[/bold yellow] sound (like in [bold white]cup[/bold white])?",
                "lesson": "Short U says 'uh' — like in [bold white]cup, bug, sun, run[/bold white].",
                "options": ["cube", "mule", "cup", "rule"],
                "answer": "c",
                "hints": ["Short U is the sound in 'uh-oh'!", "Cup: C-uh-P. Short U!"],
                "xp": 35,
            },
            {
                "id": "vp_06",
                "title": "Long A",
                "type": "quiz",
                "question": "Which word has the long [bold yellow]A[/bold yellow] sound — where it says its own name, 'AY'?",
                "lesson": "Long A says 'AY' — like in [bold white]cake, lake, name, game[/bold white]. It says its own name!",
                "options": ["cat", "cap", "cake", "can"],
                "answer": "c",
                "hints": ["Long A says its own name — AY!", "Cake: C-AY-K. Long A says 'ay'!"],
                "xp": 35,
            },
            {
                "id": "vp_boss",
                "title": "All Five Vowels",
                "type": "quiz",
                "question": "The word [bold white]bite[/bold white] has which vowel in the middle, making a long sound?",
                "lesson": "Long I says its own name — 'EYE'. In [bold white]bite, kite, like, mine[/bold white], the I says 'I'!",
                "options": ["A", "E", "I", "O"],
                "answer": "c",
                "hints": ["Bite: B-EYE-T. What vowel says 'EYE'?", "I says its own name in 'bite'!"],
                "xp": 70,
                "is_boss": True,
            },
        ],
    },

    "blend_bridge": {
        "id": "blend_bridge",
        "name": "The Blend Bridge",
        "description": "Put two consonants together",
        "level_required": 3,
        "challenges": [
            {
                "id": "bb_01",
                "title": "The BR Blend",
                "type": "quiz",
                "question": "What two letters do you hear at the start of [bold white]bread[/bold white]?",
                "lesson": "[bold yellow]BR[/bold yellow] — B and R together, fast! [bold white]Bread, brown, branch, bridge[/bold white] all start with BR.",
                "options": ["BL", "PR", "BR", "TR"],
                "answer": "c",
                "hints": ["Say 'bread' slowly: BR-ead. Two letters, one quick sound!", "B + R = BR"],
                "xp": 40,
            },
            {
                "id": "bb_02",
                "title": "The ST Blend",
                "type": "quiz",
                "question": "Which word starts with the [bold yellow]ST[/bold yellow] blend?",
                "lesson": "[bold yellow]ST[/bold yellow] — S and T together! [bold white]Star, stop, stick, storm[/bold white] all start with ST.",
                "options": ["Spin", "Star", "Train", "Frog"],
                "answer": "b",
                "hints": ["ST sounds like you're about to say STOP!", "Star — S-T-ar"],
                "xp": 40,
            },
            {
                "id": "bb_03",
                "title": "The PL Blend",
                "type": "quiz",
                "question": "What blend do you hear at the start of [bold white]plant[/bold white]?",
                "lesson": "[bold yellow]PL[/bold yellow] — P and L, side by side. [bold white]Plant, play, plate, place[/bold white] — all start with PL.",
                "options": ["FL", "GL", "BL", "PL"],
                "answer": "d",
                "hints": ["Plant, play, please — what two letters are they sharing?", "P + L = PL"],
                "xp": 40,
            },
            {
                "id": "bb_04",
                "title": "The TR Blend",
                "type": "quiz",
                "question": "Which word begins with [bold yellow]TR[/bold yellow]?",
                "lesson": "[bold yellow]TR[/bold yellow] — T and R together. [bold white]Tree, truck, train, trip[/bold white] all start with TR!",
                "options": ["Snake", "Tree", "Flower", "Crab"],
                "answer": "b",
                "hints": ["TR sounds like a truck engine starting!", "Tree: TR-ee"],
                "xp": 40,
            },
            {
                "id": "bb_05",
                "title": "The FL Blend",
                "type": "quiz",
                "question": "What blend starts the word [bold white]flower[/bold white]?",
                "lesson": "[bold yellow]FL[/bold yellow] — F and L. [bold white]Flower, fly, flag, float[/bold white]. The air flows out with FL!",
                "options": ["BL", "FR", "FL", "GL"],
                "answer": "c",
                "hints": ["Flower, fly, flag — they all start the same way!", "F + L = FL"],
                "xp": 40,
            },
            {
                "id": "bb_boss",
                "title": "Three-Letter Blends",
                "type": "quiz",
                "question": "What THREE letters do you hear at the start of [bold white]string[/bold white]?",
                "lesson": "[bold yellow]STR[/bold yellow] — S, T, and R all together! [bold white]String, strong, stream, straw[/bold white].",
                "options": ["SHR", "SPR", "STR", "SCR"],
                "answer": "c",
                "hints": ["String: S-T-R-ing. Three letters, one quick blend!", "S + T + R = STR"],
                "xp": 80,
                "is_boss": True,
            },
        ],
    },

    "word_workshop": {
        "id": "word_workshop",
        "name": "The Word Workshop",
        "description": "Build and read real words",
        "level_required": 4,
        "challenges": [
            {
                "id": "ww_01",
                "title": "Three-Letter Words",
                "type": "fill_blank",
                "question": "Fill in the missing letter:\n[bold white]C _ T[/bold white]\n(It's a fluffy animal that says meow)",
                "lesson": "Sound it out: C-?-T. What vowel sound is in the middle of [bold white]cat[/bold white]?",
                "answer": "a",
                "hints": ["Cat has the short A sound in the middle!", "C-aaa-T = CAT"],
                "xp": 45,
            },
            {
                "id": "ww_02",
                "title": "More Three-Letter Words",
                "type": "fill_blank",
                "question": "Fill in the missing letter:\n[bold white]S _ N[/bold white]\n(It shines in the sky during the day)",
                "lesson": "[bold white]Sun[/bold white] has the short U sound in the middle: S-uh-N.",
                "answer": "u",
                "hints": ["Think of a sunny day — SUN has a short U sound!", "S-uh-N = SUN"],
                "xp": 45,
            },
            {
                "id": "ww_03",
                "title": "Reading a CVC Word",
                "type": "quiz",
                "question": "What does this word say? [bold white]HOP[/bold white]",
                "lesson": "[bold white]HOP[/bold white] — H-O-P. Short O in the middle. Bunnies hop!",
                "options": ["hip", "heap", "hop", "help"],
                "answer": "c",
                "hints": ["H-O-P. Sound each letter out!", "What does a bunny do? HOP!"],
                "xp": 45,
            },
            {
                "id": "ww_04",
                "title": "Silent E Words",
                "type": "quiz",
                "question": "Add a silent E to [bold white]cap[/bold white]. What new word do you get?",
                "lesson": "A silent E at the end makes the vowel say its long sound! [bold white]cap → cape[/bold white], [bold white]pin → pine[/bold white], [bold white]hop → hope[/bold white].",
                "options": ["cup", "cape", "cop", "cap"],
                "answer": "b",
                "hints": ["Silent E is a magic letter — it changes the vowel's sound!", "cap + e = cape (like a superhero wears!)"],
                "xp": 50,
            },
            {
                "id": "ww_05",
                "title": "Compound Words",
                "type": "quiz",
                "question": "What do you get when you put [bold yellow]SUN[/bold yellow] and [bold yellow]FLOWER[/bold yellow] together?",
                "lesson": "Compound words are two words joined together! [bold white]Sun + flower = sunflower[/bold white]. The meaning is mixed together too!",
                "options": ["Raindrop", "Sunflower", "Butterfly", "Snowball"],
                "answer": "b",
                "hints": ["Sun + flower = ?", "It's a tall flower that faces the sun!"],
                "xp": 50,
            },
            {
                "id": "ww_boss",
                "title": "A Longer Word",
                "type": "quiz",
                "question": "Sound out this word: [bold white]BASKET[/bold white]\nHow many syllables (beats) does it have?",
                "lesson": "[bold white]BAS-KET[/bold white] — two syllables! Clap once for BAS, once for KET. Longer words have multiple beats.",
                "options": ["1", "2", "3", "4"],
                "answer": "b",
                "hints": ["Clap as you say it: BAS (clap) KET (clap)", "BAS-KET = two claps = two syllables!"],
                "xp": 90,
                "is_boss": True,
            },
        ],
    },

    "sentence_city": {
        "id": "sentence_city",
        "name": "Sentence City",
        "description": "Read complete sentences",
        "level_required": 5,
        "challenges": [
            {
                "id": "sc_01",
                "title": "A Simple Sentence",
                "type": "quiz",
                "question": "Read this sentence:\n[bold white]The cat sat on the mat.[/bold white]\n\nWhere did the cat sit?",
                "lesson": "A sentence tells us a complete thought. Who? (the cat) Did what? (sat) Where? (on the mat).",
                "options": ["On the floor", "On the mat", "On the bed", "In the tree"],
                "answer": "b",
                "hints": ["Read the sentence again — it tells you exactly where!", "On the...?"],
                "xp": 50,
            },
            {
                "id": "sc_02",
                "title": "Describing Words",
                "type": "quiz",
                "question": "Read this:\n[bold white]The big red ball rolled down the hill.[/bold white]\n\nWhat two words describe the ball?",
                "lesson": "Describing words (adjectives) tell us more about things. In [bold white]big red ball[/bold white], 'big' and 'red' describe the ball.",
                "options": ["round and fast", "small and blue", "big and red", "soft and heavy"],
                "answer": "c",
                "hints": ["Look for the words that come before 'ball'", "Big __ ball — what color is it?"],
                "xp": 55,
            },
            {
                "id": "sc_03",
                "title": "Action Words",
                "type": "quiz",
                "question": "Read this:\n[bold white]The happy dog jumped over the fence.[/bold white]\n\nWhat action word (verb) is in this sentence?",
                "lesson": "Action words (verbs) tell us what's happening. [bold white]Jumped[/bold white] is the action word — it tells us what the dog did.",
                "options": ["happy", "dog", "jumped", "fence"],
                "answer": "c",
                "hints": ["What did the dog DO?", "Jumped! That's the action!"],
                "xp": 55,
            },
            {
                "id": "sc_04",
                "title": "Question Sentences",
                "type": "quiz",
                "question": "Read this question:\n[bold white]Is today a sunny day?[/bold white]\n\nHow do you know this is a question?",
                "lesson": "Questions end with a question mark [bold yellow]?[/bold yellow]. They ask something instead of telling something.",
                "options": ["It starts with Is", "It ends with a question mark ?", "It has the word 'day'", "All of the above"],
                "answer": "d",
                "hints": ["Look at the punctuation at the end!", "Questions start with words like Is, Are, Can, Do — and end with ?"],
                "xp": 55,
            },
            {
                "id": "sc_05",
                "title": "Reading for Meaning",
                "type": "quiz",
                "question": "Read carefully:\n[bold white]Nell loved books more than anything. Every night she read one story before bed.[/bold white]\n\nHow often did Nell read a story?",
                "lesson": "Good readers understand the meaning behind words. [bold white]Every night[/bold white] means she read [italic]each and every[/italic] night — not just sometimes!",
                "options": ["Sometimes", "Every night", "Only on weekends", "Once a week"],
                "answer": "b",
                "hints": ["Look for the words about time — 'every night'", "Every night means each night!"],
                "xp": 60,
            },
            {
                "id": "sc_boss",
                "title": "A Whole Paragraph",
                "type": "quiz",
                "question": "Read this:\n[bold white]Puck lived inside the book. When Nell opened the pages, Puck flew out to say hello. Puck was small but very wise, and knew every letter and every word.[/bold white]\n\nWhat is this paragraph mostly about?",
                "lesson": "A paragraph is a group of sentences about one main idea. This paragraph is about Puck — who Puck is and what Puck knows.",
                "options": ["What Nell likes to eat", "Who Puck is", "How to open a book", "What letters are"],
                "answer": "b",
                "hints": ["Every sentence in this paragraph mentions Puck!", "The paragraph tells you about Puck — where Puck lives, what Puck does, what Puck knows."],
                "xp": 100,
                "is_boss": True,
            },
        ],
    },
}
