"""
zones.py — pack.py -- Sports skill pack: The Arena of Champions
"""

ZONE_ORDER = ['ball_sports', 'water_and_ice', 'track_and_field', 'olympic_history', 'fitness_and_health']

ZONES = {
    "ball_sports": {
        "id": "ball_sports",
        "name": 'Ball Sports Basics',
        "description": "Learn the rules and fun facts behind the world's favourite ball games",
        "level_required": 1,
        "challenges": [
            {
                "id": 'soccer_players',
                "question": 'How many players does each team have on the field in a soccer (football) match?',
                "type": 'quiz',
                "options": ['9', '10', '11', '12'],
                "answer": 'c',
                "lesson": 'A soccer team has 11 players on the field, including the goalkeeper. Soccer is the most popular sport in the world -- over 4 billion people follow it!',
                "hints": ["It's more than 10 but fewer than 12.", 'One of those players is the goalkeeper!'],
                "xp": 25,
            },
            {
                "id": 'basketball_hoop',
                "question": 'How high is a standard basketball hoop from the ground?',
                "type": 'quiz',
                "options": ['8 feet', '10 feet', '12 feet', '15 feet'],
                "answer": 'b',
                "lesson": 'A basketball hoop is exactly 10 feet (about 3 metres) above the ground. This height has stayed the same since Dr. James Naismith invented basketball in 1891!',
                "hints": ["It's the same height everywhere in the world -- from kids' leagues to the NBA.", "Think of a number that's easy to remember!"],
                "xp": 25,
            },
            {
                "id": 'tennis_scoring',
                "question": "In tennis, what does the word 'love' mean?",
                "type": 'quiz',
                "options": ['A perfect serve', 'Zero points', 'Winning the match', 'A tie game'],
                "answer": 'b',
                "lesson": "In tennis, 'love' means zero. So a score of 30-love means 30 to nothing! The word may come from the French word 'l'oeuf' (the egg), because an egg looks like a zero.",
                "hints": ["It's a score -- and it's the one nobody wants!", "If you have 'love', you haven't scored yet."],
                "xp": 25,
            },
            {
                "id": 'baseball_bases',
                "question": 'How many bases are there on a baseball diamond (including home plate)?',
                "type": 'quiz',
                "options": ['3', '4', '5', '6'],
                "answer": 'b',
                "lesson": 'A baseball diamond has 4 bases: first base, second base, third base, and home plate. A player who runs all the way around scores a run!',
                "hints": ['A runner goes: home, first, second, third, then back to...', "It's called a diamond because of its four corners."],
                "xp": 25,
            },
            {
                "id": 'volleyball_hits',
                "question": 'In volleyball, how many times can a team touch the ball before they must send it over the net?',
                "type": 'quiz',
                "options": ['1', '2', '3', '4'],
                "answer": 'c',
                "lesson": 'A volleyball team gets up to 3 touches to return the ball over the net. The usual pattern is: bump (pass), set (lift), spike (attack). Teamwork at its best!',
                "hints": ['Teams usually bump it, set it, and then...', 'Three touches: pass, set, attack!'],
                "xp": 30,
            },
            {
                "id": 'golf_holes',
                "question": 'How many holes are on a standard full-length golf course?',
                "type": 'text',
                "options": [],
                "answer": '18',
                "lesson": "A standard golf course has 18 holes. The game was invented in Scotland over 500 years ago. A 'hole in one' -- getting the ball in the cup with a single shot -- is one of the rarest feats in sports!",
                "hints": ["It's more than 10 but fewer than 20.", "A 'front nine' plus a 'back nine' equals..."],
                "xp": 30,
            },
            {
                "id": 'cricket_bat_shape',
                "question": 'In cricket, what is the name for a score of zero by a batter?',
                "type": 'quiz',
                "options": ['Nil', 'Duck', 'Goose', 'Blank'],
                "answer": 'b',
                "lesson": "In cricket, scoring zero is called a 'duck' -- because a zero looks like a duck's egg! Cricket is hugely popular in countries like India, England, and Australia, and has over 2.5 billion fans worldwide.",
                "hints": ["It's named after a bird!", 'A zero looks like an egg, and this bird lays eggs...'],
                "xp": 30,
            },
            {
                "id": 'boss_ball_sports',
                "question": 'Which sport is played in the FIFA World Cup, watched by nearly half the people on Earth?',
                "type": 'quiz',
                "options": ['Basketball', 'Cricket', 'Soccer (Football)', 'Tennis'],
                "answer": 'c',
                "lesson": 'The FIFA World Cup is a soccer (football) tournament held every four years. The 2022 final was watched by about 1.5 billion people -- making it one of the most-watched events in human history!',
                "hints": ["It's played with your feet more than your hands.", "In most countries, this sport is simply called 'football'."],
                "xp": 40,
            },
        ],
    },
    "water_and_ice": {
        "id": "water_and_ice",
        "name": 'Water & Ice Sports',
        "description": 'Explore the thrilling world of swimming, diving, skating, and more',
        "level_required": 2,
        "challenges": [
            {
                "id": 'swimming_strokes',
                "question": 'Which of these is NOT one of the four official Olympic swimming strokes?',
                "type": 'quiz',
                "options": ['Backstroke', 'Doggy paddle', 'Butterfly', 'Breaststroke'],
                "answer": 'b',
                "lesson": 'The four official Olympic swimming strokes are freestyle (front crawl), backstroke, breaststroke, and butterfly. The doggy paddle is fun but not a competitive stroke!',
                "hints": ['Three of these are in the Olympics. One is what puppies do!', 'The four Olympic strokes are freestyle, backstroke, breaststroke, and butterfly.'],
                "xp": 25,
            },
            {
                "id": 'ice_skating_jump',
                "question": 'In figure skating, what is the surface of the ice rink made of?',
                "type": 'quiz',
                "options": ['Frozen milk', 'Frozen water (ice)', 'Plastic', 'Glass'],
                "answer": 'b',
                "lesson": 'Ice rinks are made of frozen water, kept at about -4 degrees Celsius. A Zamboni machine smooths the ice between skating sessions. Figure skaters can spin at over 300 revolutions per minute!',
                "hints": ["It's cold, slippery, and melts when it gets warm!", "It's the same stuff that comes out of your freezer."],
                "xp": 25,
            },
            {
                "id": 'surfing_origin',
                "question": 'Surfing was invented by the people of which island group?',
                "type": 'quiz',
                "options": ['Japan', 'Hawaii', 'Iceland', 'England'],
                "answer": 'b',
                "lesson": "Surfing was invented by the Polynesian people of Hawaii hundreds of years ago. In Hawaiian culture, surfing was called 'he'e nalu' -- wave sliding. It became an Olympic sport in 2020!",
                "hints": ['These islands are in the middle of the Pacific Ocean.', 'Ancient Polynesian royalty rode wooden boards on waves here.'],
                "xp": 25,
            },
            {
                "id": 'diving_score',
                "question": 'In Olympic diving, what is the highest score a single judge can give for one dive?',
                "type": 'quiz',
                "options": ['5', '8', '10', '100'],
                "answer": 'c',
                "lesson": 'Each diving judge scores a dive from 0 to 10. A perfect 10 means flawless entry, technique, and form. The scores are then multiplied by a difficulty rating -- so harder dives can earn more points!',
                "hints": ['When a dive is absolutely flawless, it gets the maximum...', "It's the same as a 'perfect score' in gymnastics."],
                "xp": 30,
            },
            {
                "id": 'hockey_puck',
                "question": 'What is the flat rubber disc called that players hit in ice hockey?',
                "type": 'text',
                "options": [],
                "answer": 'puck',
                "lesson": "The rubber disc in ice hockey is called a puck. It's about 1 inch thick, 3 inches wide, and can be hit at speeds over 100 miles per hour! Hockey pucks are frozen before games to reduce bouncing.",
                "hints": ["It's the same name as a certain fairy friend of yours!", "It's small, black, round, flat, and made of rubber."],
                "xp": 30,
            },
            {
                "id": 'water_polo_treading',
                "question": 'In water polo, are players allowed to touch the bottom of the pool during play?',
                "type": 'quiz',
                "options": ['Yes, any time', 'No, they must tread water the whole time', 'Only the goalkeeper', 'Only when scoring'],
                "answer": 'b',
                "lesson": "Water polo players must tread water for the entire game -- they're not allowed to touch the bottom or sides of the pool! A game has four 8-minute periods. It's one of the most exhausting sports in the world.",
                "hints": ['The pool is deep -- very deep!', 'Players must keep themselves afloat the entire game.'],
                "xp": 30,
            },
            {
                "id": 'rowing_crew',
                "question": 'In rowing, what is the person called who sits at the back of the boat and shouts instructions but does NOT row?',
                "type": 'quiz',
                "options": ['Captain', 'Coxswain', 'Coach', 'Referee'],
                "answer": 'b',
                "lesson": "The coxswain (say 'COX-in') steers the boat, keeps the rhythm, and motivates the rowers. They are usually the smallest and lightest person on the team. Teamwork and rhythm are everything in rowing!",
                "hints": ['This person steers the boat and keeps the rhythm.', "The word starts with 'cox'..."],
                "xp": 30,
            },
            {
                "id": 'boss_water_ice',
                "question": 'Which American swimmer won 8 gold medals at the 2008 Beijing Olympics, the most gold medals ever won at a single Games?',
                "type": 'text',
                "options": [],
                "answer": 'michael phelps',
                "lesson": 'Michael Phelps won 8 golds at Beijing 2008 and 23 golds in his career -- the most Olympic gold medals EVER. He could swim 100m butterfly in under 50 seconds. His wingspan is wider than he is tall!',
                "hints": ["His last name starts with 'Ph'.", "He's been called the greatest Olympian of all time, with 23 gold medals total."],
                "xp": 45,
            },
        ],
    },
    "track_and_field": {
        "id": "track_and_field",
        "name": 'Track & Field',
        "description": 'Sprint, jump, and throw your way through the oldest sports on Earth',
        "level_required": 3,
        "challenges": [
            {
                "id": 'sprint_distance',
                "question": 'How long is the shortest sprint race in the Olympics?',
                "type": 'quiz',
                "options": ['50 metres', '100 metres', '200 metres', '400 metres'],
                "answer": 'b',
                "lesson": "The 100-metre dash is the shortest and fastest Olympic race. The world record is 9.58 seconds, set by Usain Bolt in 2009. That's faster than most people can blink ten times!",
                "hints": ["It's about the length of a football field.", "Usain Bolt's most famous race was this distance."],
                "xp": 25,
            },
            {
                "id": 'marathon_origin',
                "question": 'The marathon race is named after a place in which country?',
                "type": 'quiz',
                "options": ['Italy', 'Greece', 'Egypt', 'France'],
                "answer": 'b',
                "lesson": "Marathon is a town in Greece. Legend says a soldier named Pheidippides ran about 25 miles from Marathon to Athens to announce a military victory in 490 BC. Today's marathon is 26.2 miles (42.2 km)!",
                "hints": ['The story goes that a messenger ran from a battlefield to a city to deliver news of victory.', 'This country is where the ancient Olympics began.'],
                "xp": 25,
            },
            {
                "id": 'hurdles_jump',
                "question": 'In a hurdles race, what happens if an athlete knocks over a hurdle?',
                "type": 'quiz',
                "options": ['They are disqualified', 'They must stop and fix it', 'They can keep running -- no penalty', 'They lose 2 seconds'],
                "answer": 'c',
                "lesson": 'In hurdle racing, athletes can knock over hurdles without being disqualified. But hitting them slows you down! The trick is to jump just high enough to clear each one -- wasting no energy going too high.',
                "hints": ['Hurdles are designed to fall over safely.', "Knocking them down slows you down, but you don't get a penalty."],
                "xp": 30,
            },
            {
                "id": 'long_jump_landing',
                "question": 'In the long jump, where does an athlete land?',
                "type": 'quiz',
                "options": ['On a mat', 'In a sandpit', 'On grass', 'In water'],
                "answer": 'b',
                "lesson": 'Long jumpers land in a sandpit to cushion their landing. The world record is 8.95 metres (29 feet!) set by Mike Powell in 1991. Athletes sprint down a runway and launch from a wooden board.',
                "hints": ["It's soft and cushions the landing.", 'You might find this material at a beach or playground.'],
                "xp": 25,
            },
            {
                "id": 'javelin_throw',
                "question": 'What is the long, thin object thrown in the javelin event called?',
                "type": 'text',
                "options": [],
                "answer": 'javelin',
                "lesson": "A javelin is a lightweight spear about 2.6 metres long. Athletes run and throw it as far as they can. The ancient Greeks used javelin throwing as military training -- now it's an Olympic event!",
                "hints": ['The event is named after the object!', "It's like a spear or lance."],
                "xp": 25,
            },
            {
                "id": 'relay_baton',
                "question": 'In a relay race, what do runners pass to the next teammate?',
                "type": 'quiz',
                "options": ['A flag', 'A baton', 'A ball', 'A ribbon'],
                "answer": 'b',
                "lesson": 'Relay runners pass a baton -- a short, hollow tube. The exchange must happen inside a 20-metre zone. Dropping the baton is one of the most heartbreaking moments in track and field!',
                "hints": ["It's a short stick or tube.", 'If you drop it, your team could lose the race!'],
                "xp": 25,
            },
            {
                "id": 'high_jump_technique',
                "question": 'In the high jump, most athletes go over the bar in what position?',
                "type": 'quiz',
                "options": ['Feet first', 'Backwards, arching over the bar', 'Diving headfirst', 'Sitting down'],
                "answer": 'b',
                "lesson": "The 'Fosbury Flop' changed high jumping forever. Dick Fosbury surprised the world at the 1968 Olympics by going over the bar backwards. Before that, jumpers went face-down! Now everyone uses his technique.",
                "hints": ['This technique was invented by Dick Fosbury in 1968.', "The jumper's back faces the bar as they go over."],
                "xp": 30,
            },
            {
                "id": 'boss_track_field',
                "question": 'Which Jamaican sprinter holds the world record for the 100m dash at 9.58 seconds and is known as the fastest human ever?',
                "type": 'text',
                "options": [],
                "answer": 'usain bolt',
                "lesson": "Usain Bolt ran 100m in 9.58 seconds and 200m in 19.19 seconds -- both world records. He won 8 Olympic gold medals and his top speed was nearly 45 km/h (28 mph). His nickname is 'Lightning Bolt'!",
                "hints": ['His last name is a word that means a flash of lightning.', "He's from Jamaica and his signature pose is pointing to the sky like an archer."],
                "xp": 45,
            },
        ],
    },
    "olympic_history": {
        "id": "olympic_history",
        "name": 'Olympic History',
        "description": 'Journey from ancient Greece to the modern Games',
        "level_required": 4,
        "challenges": [
            {
                "id": 'olympic_rings',
                "question": 'How many rings are on the Olympic flag?',
                "type": 'quiz',
                "options": ['3', '4', '5', '6'],
                "answer": 'c',
                "lesson": "The Olympic flag has 5 interlocking rings representing the five continents: Africa, the Americas, Asia, Europe, and Oceania. Every country's flag contains at least one of the ring colours!",
                "hints": ['Each ring represents one of the five continents.', 'They are blue, yellow, black, green, and red.'],
                "xp": 25,
            },
            {
                "id": 'ancient_olympics',
                "question": 'In which ancient Greek city were the original Olympic Games held?',
                "type": 'text',
                "options": [],
                "answer": 'olympia',
                "lesson": "The ancient Olympic Games were held at Olympia, Greece, starting around 776 BC. They ran for over 1,000 years! Athletes competed in the nude, and the only event at first was a single foot race called the 'stadion'.",
                "hints": ['The Games are named after this place!', "It starts with 'O' and is in Greece."],
                "xp": 25,
            },
            {
                "id": 'modern_olympics_year',
                "question": 'In what year were the first modern Olympic Games held?',
                "type": 'quiz',
                "options": ['1776', '1896', '1900', '1924'],
                "answer": 'b',
                "lesson": 'The first modern Olympics were held in Athens, Greece, in 1896. Baron Pierre de Coubertin of France organized the revival. Only 14 countries and 241 athletes competed -- today, over 200 nations take part!',
                "hints": ['It was in the late 1800s, in Athens, Greece.', 'A Frenchman named Pierre de Coubertin helped bring the Games back.'],
                "xp": 30,
            },
            {
                "id": 'winter_olympics',
                "question": 'The Winter Olympics feature sports played on snow and ice. Which of these is a Winter Olympic sport?',
                "type": 'quiz',
                "options": ['Swimming', 'Gymnastics', 'Figure skating', 'Tennis'],
                "answer": 'c',
                "lesson": 'The Winter Olympics include sports like figure skating, skiing, snowboarding, ice hockey, and bobsled. The first Winter Olympics were held in 1924 in Chamonix, France. They happen every 4 years!',
                "hints": ['Winter sports need cold weather!', 'Think about sports on ice or snow.'],
                "xp": 25,
            },
            {
                "id": 'olympic_torch',
                "question": 'Before each Olympic Games, a flame is lit in Greece and carried to the host city. What is this tradition called?',
                "type": 'quiz',
                "options": ['The Fire Walk', 'The Torch Relay', 'The Flame Dance', 'The Light Parade'],
                "answer": 'b',
                "lesson": 'The Olympic Torch Relay begins at Olympia, Greece, where the flame is lit using sunlight and a mirror. Thousands of runners carry it to the host city. It lights the Olympic cauldron at the opening ceremony!',
                "hints": ['Runners carry a burning torch from person to person.', "The word 'relay' means passing something from one person to the next."],
                "xp": 30,
            },
            {
                "id": 'paralympics',
                "question": 'What are the Games called that are held right after the Olympics for athletes with disabilities?',
                "type": 'quiz',
                "options": ['The Super Games', 'The Paralympics', 'The Extra Games', 'The Hero Games'],
                "answer": 'b',
                "lesson": "The Paralympics are held right after the Olympics in the same city. 'Para' means 'beside' -- these Games run alongside the Olympics. Paralympic athletes are incredible -- they compete in wheelchairs, with prosthetics, and with visual impairments!",
                "hints": ["The word starts with 'Para', meaning 'beside' or 'alongside'.", 'These Games run parallel to the Olympics.'],
                "xp": 30,
            },
            {
                "id": 'olympic_motto',
                "question": 'What is the Olympic motto?',
                "type": 'quiz',
                "options": ['Win at all costs', 'Faster, Higher, Stronger -- Together', 'Be the best', 'Never give up'],
                "answer": 'b',
                "lesson": "The Olympic motto is 'Citius, Altius, Fortius -- Communiter' which means 'Faster, Higher, Stronger -- Together.' The word 'Together' was added in 2021 to show that we achieve more when we work as one.",
                "hints": ["It was originally in Latin: 'Citius, Altius, Fortius'.", 'A new word was added in 2021 to emphasise unity.'],
                "xp": 30,
            },
            {
                "id": 'boss_olympic_history',
                "question": 'What is the name of the ancient Greek city where the original Olympic Games were held for over 1,000 years?',
                "type": 'text',
                "options": [],
                "answer": 'olympia',
                "lesson": 'Olympia was a sanctuary in western Greece where the Olympic Games were held from 776 BC to 393 AD -- over 1,100 years! The ruins of the ancient stadium and temples can still be visited today.',
                "hints": ['The Games were named after this city.', "It's in Greece and starts with the letter 'O'."],
                "xp": 45,
            },
        ],
    },
    "fitness_and_health": {
        "id": "fitness_and_health",
        "name": 'Fitness & Health',
        "description": 'Discover how exercise, nutrition, and rest build real-life champions',
        "level_required": 5,
        "challenges": [
            {
                "id": 'heart_muscle',
                "question": 'Your heart is a special kind of muscle. About how many times does it beat in one day?',
                "type": 'quiz',
                "options": ['1,000', '10,000', '100,000', '1,000,000'],
                "answer": 'c',
                "lesson": "Your heart beats about 100,000 times every single day! That's over 35 million times a year. Exercise makes your heart stronger so each beat pumps more blood, meaning it can work more efficiently.",
                "hints": ['It beats about 60-100 times per minute.', '60 beats x 60 minutes x 24 hours = a LOT!'],
                "xp": 25,
            },
            {
                "id": 'water_importance',
                "question": 'About how much of your body is made up of water?',
                "type": 'quiz',
                "options": ['10%', '30%', '60%', '90%'],
                "answer": 'c',
                "lesson": "About 60% of your body is water! That's why staying hydrated is so important, especially when you exercise. Water helps your body cool down through sweat, carries nutrients to your cells, and keeps your brain sharp.",
                "hints": ["It's more than half!", 'Your brain is about 75% water, and your blood is about 90% water.'],
                "xp": 25,
            },
            {
                "id": 'stretching_warmup',
                "question": 'Why should you warm up and stretch before playing sports?',
                "type": 'quiz',
                "options": ['To show off your flexibility', 'To help prevent injuries and get your muscles ready', 'Because coaches like it', 'To waste time before the game'],
                "answer": 'b',
                "lesson": 'Warming up raises your body temperature and gets blood flowing to your muscles. Stretching makes muscles flexible and less likely to tear. Even professional athletes spend 15-30 minutes warming up before every game!',
                "hints": ['Cold muscles are more likely to get hurt.', 'Warming up gets blood flowing to your muscles.'],
                "xp": 25,
            },
            {
                "id": 'sleep_hours',
                "question": 'How many hours of sleep do kids ages 6-12 need each night?',
                "type": 'quiz',
                "options": ['5-6 hours', '7-8 hours', '9-12 hours', '14-16 hours'],
                "answer": 'c',
                "lesson": 'Kids ages 6-12 need 9-12 hours of sleep every night! During sleep, your body repairs muscles, your brain organises memories, and growth hormones are released. Athletes know that sleep is a superpower!',
                "hints": ['Kids need more sleep than grown-ups!', 'Your body and brain grow and repair while you sleep.'],
                "xp": 30,
            },
            {
                "id": 'healthy_plate',
                "question": 'Which food group gives you the most quick energy for sports?',
                "type": 'quiz',
                "options": ['Candy and sweets', 'Fruits, vegetables, and whole grains', 'Only meat', 'Only water'],
                "answer": 'b',
                "lesson": "Fruits, vegetables, and whole grains are packed with carbohydrates -- your body's favourite fuel for exercise. Unlike candy (which gives a quick spike then a crash), these foods give steady, lasting energy!",
                "hints": ['These foods give you energy that lasts, not just a quick sugar rush.', 'Whole grains, fruits, and veggies are packed with good carbohydrates.'],
                "xp": 30,
            },
            {
                "id": 'teamwork_matters',
                "question": 'What is the most important quality of a great team?',
                "type": 'quiz',
                "options": ['Having the tallest players', 'Everyone working together and communicating', 'Having the most expensive equipment', 'Never letting anyone else touch the ball'],
                "answer": 'b',
                "lesson": "Great teams communicate, trust each other, and work together toward a common goal. Even the most talented individual can't beat a well-coordinated team. Teamwork is a skill that helps in sports AND in life!",
                "hints": ["It's not about one person -- it's about all of them.", 'Talking, listening, and trusting each other.'],
                "xp": 30,
            },
            {
                "id": 'sportsmanship',
                "question": 'What is the word for playing fairly, respecting opponents, and being gracious whether you win or lose?',
                "type": 'text',
                "options": [],
                "answer": 'sportsmanship',
                "lesson": 'Sportsmanship means playing fairly, respecting your opponents, following the rules, and being a good winner AND a good loser. True champions shake hands after every game, no matter the result.',
                "hints": ["It ends in '-ship' and starts with 'sports'.", 'It means being a good sport!'],
                "xp": 30,
            },
            {
                "id": 'boss_fitness_health',
                "question": 'What is the BEST way to keep your heart strong and healthy for your whole life?',
                "type": 'quiz',
                "options": ["Never exercise so you don't wear it out", 'Regular exercise, healthy food, enough sleep, and staying hydrated', 'Only eat protein', 'Play video games for 8 hours a day'],
                "answer": 'b',
                "lesson": "A healthy heart needs regular exercise (at least 60 minutes a day for kids!), nutritious food, plenty of water, and 9-12 hours of sleep. These habits don't just help your heart -- they make your whole body and mind stronger!",
                "hints": ["It's a combination of good habits, not just one thing.", 'Move your body, eat well, drink water, and sleep enough!'],
                "xp": 50,
            },
        ],
    },
}
