"""
zones.py — pack.py — The Shape Shifter's Garden skill pack.
"""

ZONE_ORDER = ['basic_shapes', '3d_shapes', 'colors_and_color_mixing', 'symmetry_and_patterns', 'shapes_in_nature']

ZONES = {
    "basic_shapes": {
        "id": "basic_shapes",
        "name": 'The Flat-Land Meadow',
        "description": 'Meet circles, squares, triangles, and more 2D friends!',
        "level_required": 1,
        "challenges": [
            {
                "id": 'basic_circle',
                "question": 'Which shape has no corners and no straight sides — just one smooth, round edge?',
                "type": 'quiz',
                "options": ['a) Square', 'b) Triangle', 'c) Circle', 'd) Rectangle'],
                "answer": 'c',
                "lesson": 'A circle is perfectly round with no corners at all! Every point on its edge is the same distance from the center. Wheels, coins, and pizzas are all circles.',
                "xp": 10,
            },
            {
                "id": 'basic_triangle_sides',
                "question": 'How many sides does a triangle have?',
                "type": 'quiz',
                "options": ['a) 2', 'b) 3', 'c) 4', 'd) 5'],
                "answer": 'b',
                "lesson": "A triangle always has exactly 3 sides and 3 corners (vertices). The word 'tri' means three — like a tricycle has 3 wheels! Triangles are one of the strongest shapes in building.",
                "xp": 10,
            },
            {
                "id": 'basic_square_vs_rectangle',
                "question": 'What makes a square special compared to a rectangle?',
                "type": 'quiz',
                "options": ['a) A square has 4 corners but a rectangle has 3', 'b) A square has all 4 sides the same length', 'c) A square is always bigger', 'd) A rectangle has curved sides'],
                "answer": 'b',
                "lesson": 'Both squares and rectangles have 4 sides and 4 right-angle corners. But a square is extra special because ALL 4 sides are the same length. A rectangle can have 2 long sides and 2 short sides.',
                "xp": 10,
            },
            {
                "id": 'basic_hexagon',
                "question": 'A hexagon has how many sides?',
                "type": 'quiz',
                "options": ['a) 5', 'b) 6', 'c) 7', 'd) 8'],
                "answer": 'b',
                "lesson": "A hexagon has 6 sides! 'Hex' means six. Honeybees build their honeycombs out of hexagons because that shape fits together perfectly with no gaps and uses the least wax. Clever bees!",
                "xp": 10,
            },
            {
                "id": 'basic_oval_name',
                "question": 'What is the name of a shape that looks like a stretched-out circle — like an egg?',
                "type": 'text',
                "options": [],
                "answer": 'oval',
                "lesson": 'An oval (also called an ellipse) is like a circle that has been gently stretched. Eggs, faces, and even the orbits of planets around the Sun are oval-shaped!',
                "xp": 15,
            },
            {
                "id": 'basic_octagon',
                "question": 'Stop signs are what shape?',
                "type": 'quiz',
                "options": ['a) Hexagon (6 sides)', 'b) Pentagon (5 sides)', 'c) Octagon (8 sides)', 'd) Circle (0 sides)'],
                "answer": 'c',
                "lesson": "Stop signs are octagons — shapes with 8 sides! 'Octo' means eight, just like an octopus has 8 arms. The unique shape helps drivers recognize the sign instantly, even from far away.",
                "xp": 10,
            },
            {
                "id": 'basic_pentagon',
                "question": 'The Pentagon building in Washington, D.C. is named after its shape. How many sides does a pentagon have?',
                "type": 'quiz',
                "options": ['a) 4', 'b) 5', 'c) 6', 'd) 8'],
                "answer": 'b',
                "lesson": "A pentagon has 5 sides and 5 corners. 'Penta' means five. The Pentagon in Washington, D.C. is one of the largest office buildings in the world and is shaped like a giant pentagon when seen from above!",
                "xp": 10,
            },
            {
                "id": 'basic_sides_counting',
                "question": 'How many sides does a rectangle have?',
                "type": 'text',
                "options": [],
                "answer": '4',
                "lesson": 'A rectangle has 4 sides — two pairs of equal-length sides. Doors, books, screens, and windows are all rectangles. It is one of the most common shapes in buildings and everyday objects!',
                "xp": 15,
            },
        ],
    },
    "3d_shapes": {
        "id": "3d_shapes",
        "name": 'The Solid Shape Workshop',
        "description": 'Discover cubes, spheres, cones, and other 3D shapes you can hold!',
        "level_required": 1,
        "challenges": [
            {
                "id": '3d_sphere',
                "question": 'A ball is an example of which 3D shape?',
                "type": 'quiz',
                "options": ['a) Cube', 'b) Cone', 'c) Sphere', 'd) Cylinder'],
                "answer": 'c',
                "lesson": 'A sphere is a perfectly round 3D shape — like a ball, a globe, or a marble. Every point on its surface is the same distance from the center, just like a circle, but in all directions!',
                "xp": 10,
            },
            {
                "id": '3d_cube_faces',
                "question": 'How many flat faces does a cube have?',
                "type": 'quiz',
                "options": ['a) 4', 'b) 5', 'c) 6', 'd) 8'],
                "answer": 'c',
                "lesson": 'A cube has 6 flat square faces, 12 edges, and 8 corners (vertices). Dice, ice cubes, and some building blocks are all cubes. Every face of a cube is a perfect square!',
                "xp": 10,
            },
            {
                "id": '3d_cone_example',
                "question": 'Which of these is shaped like a cone?',
                "type": 'quiz',
                "options": ['a) A soccer ball', 'b) An ice cream cone', 'c) A cereal box', 'd) A can of soup'],
                "answer": 'b',
                "lesson": 'A cone has a circular base and comes to a point at the top. Ice cream cones, party hats, and traffic cones are all cone-shaped! A cone has 1 flat face (the bottom circle) and 1 curved surface.',
                "xp": 10,
            },
            {
                "id": '3d_cylinder',
                "question": 'A can of soup is an example of which 3D shape?',
                "type": 'quiz',
                "options": ['a) Sphere', 'b) Pyramid', 'c) Cube', 'd) Cylinder'],
                "answer": 'd',
                "lesson": 'A cylinder has 2 circular faces (top and bottom) connected by a curved surface. Cans, drinking glasses, batteries, and rolling pins are all cylinders. If you unroll the curved part, it becomes a rectangle!',
                "xp": 10,
            },
            {
                "id": '3d_pyramid',
                "question": 'The Great Pyramid of Giza has a square base and triangular sides that meet at a point. What is this shape called?',
                "type": 'quiz',
                "options": ['a) Prism', 'b) Pyramid', 'c) Cone', 'd) Cube'],
                "answer": 'b',
                "lesson": 'A pyramid has a flat base (often a square) and triangular sides that all meet at a single point at the top. The Great Pyramid in Egypt was built over 4,500 years ago and is one of the oldest structures still standing!',
                "xp": 10,
            },
            {
                "id": '3d_flat_vs_solid',
                "question": 'What is the difference between a 2D shape and a 3D shape?',
                "type": 'quiz',
                "options": ['a) 2D shapes are bigger', 'b) 3D shapes have depth — you can pick them up', 'c) 2D shapes are always colorful', 'd) 3D shapes only exist in computers'],
                "answer": 'b',
                "lesson": '2D (two-dimensional) shapes are flat — they have length and width but no depth. You can draw them on paper. 3D (three-dimensional) shapes have depth too — they take up space and you can hold them in your hand!',
                "xp": 10,
            },
            {
                "id": '3d_prism_name',
                "question": 'A shape like a Toblerone chocolate box has triangle ends and rectangular sides. What is this 3D shape called?',
                "type": 'text',
                "options": [],
                "answer": 'prism',
                "lesson": 'A triangular prism has 2 triangle faces on the ends and 3 rectangle faces on the sides. Prisms can also separate white light into a rainbow of colors! Tents and some rooftops are prism-shaped.',
                "xp": 15,
            },
            {
                "id": '3d_edges_cube',
                "question": 'How many edges (the lines where two faces meet) does a cube have?',
                "type": 'text',
                "options": [],
                "answer": '12',
                "lesson": "A cube has 12 edges — 4 on top, 4 on the bottom, and 4 connecting the top to the bottom. Fun fact: if you cut along 7 edges of a cube and unfold it, you get a cross-shaped flat pattern called a 'net'!",
                "xp": 15,
            },
        ],
    },
    "colors_and_color_mixing": {
        "id": "colors_and_color_mixing",
        "name": 'The Rainbow Workshop',
        "description": 'Discover primary colors, secondary colors, and the magic of mixing!',
        "level_required": 1,
        "challenges": [
            {
                "id": 'colors_primary',
                "question": "Which three colors are called 'primary colors' because they cannot be made by mixing other colors?",
                "type": 'quiz',
                "options": ['a) Green, orange, purple', 'b) Red, yellow, blue', 'c) Pink, white, black', 'd) Brown, gray, silver'],
                "answer": 'b',
                "lesson": "Red, yellow, and blue are the primary colors! They are called 'primary' because you cannot make them by mixing other colors together, but you CAN mix them to create every other color in the rainbow.",
                "xp": 10,
            },
            {
                "id": 'colors_mix_red_yellow',
                "question": 'What color do you get when you mix red and yellow paint together?',
                "type": 'quiz',
                "options": ['a) Purple', 'b) Green', 'c) Orange', 'd) Brown'],
                "answer": 'c',
                "lesson": "Red + yellow = orange! Orange is a 'secondary color' because it is made by mixing two primary colors. Oranges, sunsets, and autumn leaves are all this beautiful warm color.",
                "xp": 10,
            },
            {
                "id": 'colors_mix_blue_yellow',
                "question": 'What color do you get when you mix blue and yellow?',
                "type": 'quiz',
                "options": ['a) Red', 'b) Green', 'c) Purple', 'd) Orange'],
                "answer": 'b',
                "lesson": 'Blue + yellow = green! Green is the color of grass, leaves, and frogs. It is another secondary color. Almost all the green you see in nature comes from a pigment called chlorophyll in plants.',
                "xp": 10,
            },
            {
                "id": 'colors_mix_red_blue',
                "question": 'What new color appears when you mix red and blue together?',
                "type": 'quiz',
                "options": ['a) Orange', 'b) Green', 'c) Yellow', 'd) Purple'],
                "answer": 'd',
                "lesson": 'Red + blue = purple (also called violet)! Purple is the third secondary color. In ancient times, purple dye was so rare and expensive that only kings and queens could afford to wear it!',
                "xp": 10,
            },
            {
                "id": 'colors_warm_cool',
                "question": "Which group of colors is called 'warm colors' because they remind us of fire and sunshine?",
                "type": 'quiz',
                "options": ['a) Blue, green, purple', 'b) Red, orange, yellow', 'c) Black, white, gray', 'd) Pink, lavender, mint'],
                "answer": 'b',
                "lesson": 'Red, orange, and yellow are warm colors — they remind us of fire, the sun, and hot things. Blue, green, and purple are cool colors — they make us think of water, ice, and shade. Artists use warm and cool colors to create feelings in their paintings!',
                "xp": 10,
            },
            {
                "id": 'colors_rainbow_order',
                "question": 'The colors of the rainbow in order are: Red, Orange, Yellow, Green, Blue, Indigo, and _____. What is the last color?',
                "type": 'text',
                "options": [],
                "answer": 'violet',
                "lesson": 'The rainbow colors are Red, Orange, Yellow, Green, Blue, Indigo, Violet — often remembered as ROY G. BIV! A rainbow appears when sunlight passes through raindrops and splits into its seven colors. Each raindrop acts like a tiny prism!',
                "xp": 15,
            },
            {
                "id": 'colors_white_light',
                "question": 'What happens when you shine all the colors of light together?',
                "type": 'quiz',
                "options": ['a) You get black', 'b) You get brown', 'c) You get white light', 'd) You get gray'],
                "answer": 'c',
                "lesson": 'When all colors of light are combined, they make white light! This is the opposite of mixing paint. With paint, mixing all colors makes a muddy brown. With light, mixing all colors makes white. Isaac Newton proved this with a prism in 1666!',
                "xp": 10,
            },
            {
                "id": 'colors_complementary',
                "question": 'Red and green are on opposite sides of the color wheel. What are colors on opposite sides called?',
                "type": 'quiz',
                "options": ['a) Primary colors', 'b) Complementary colors', 'c) Warm colors', 'd) Cool colors'],
                "answer": 'b',
                "lesson": 'Colors on opposite sides of the color wheel are called complementary colors! Red and green, blue and orange, yellow and purple are complementary pairs. When placed next to each other, they make each other look brighter and more vivid.',
                "xp": 10,
            },
        ],
    },
    "symmetry_and_patterns": {
        "id": "symmetry_and_patterns",
        "name": 'The Mirror Garden',
        "description": 'Discover symmetry, reflections, and repeating patterns all around you!',
        "level_required": 1,
        "challenges": [
            {
                "id": 'sym_butterfly',
                "question": "A butterfly's wings look the same on both sides. What is this called?",
                "type": 'quiz',
                "options": ['a) Camouflage', 'b) Symmetry', 'c) Rotation', 'd) Tessellation'],
                "answer": 'b',
                "lesson": 'Symmetry means one side is a mirror image of the other! If you draw a line down the middle of a butterfly, both halves match. Human faces, leaves, and snowflakes all have symmetry too.',
                "xp": 10,
            },
            {
                "id": 'sym_line_of_symmetry',
                "question": 'If you fold a heart shape in half and both sides match perfectly, what is the fold line called?',
                "type": 'quiz',
                "options": ['a) The edge', 'b) The line of symmetry', 'c) The perimeter', 'd) The diagonal'],
                "answer": 'b',
                "lesson": 'The line of symmetry is an imaginary line where you could fold a shape and both halves would match exactly. Some shapes have more than one line of symmetry — a square has 4, and a circle has infinitely many!',
                "xp": 10,
            },
            {
                "id": 'sym_pattern_definition',
                "question": 'What makes something a pattern?',
                "type": 'quiz',
                "options": ['a) It is very colorful', 'b) It repeats in a predictable way', 'c) It is always made of squares', 'd) It has to be drawn by an artist'],
                "answer": 'b',
                "lesson": 'A pattern is something that repeats in a regular, predictable way. Circle-square-circle-square is a pattern! Patterns appear everywhere — in wallpaper, music, seasons, and even your heartbeat.',
                "xp": 10,
            },
            {
                "id": 'sym_tessellation',
                "question": 'When shapes fit together perfectly with no gaps and no overlaps — like tiles on a floor — what is that called?',
                "type": 'quiz',
                "options": ['a) A mosaic', 'b) A collage', 'c) A tessellation', 'd) A sculpture'],
                "answer": 'c',
                "lesson": 'A tessellation is when shapes tile together perfectly — no gaps, no overlaps! Squares, triangles, and hexagons can all tessellate. The artist M.C. Escher was famous for making amazing tessellations with birds, fish, and lizards.',
                "xp": 10,
            },
            {
                "id": 'sym_snowflake',
                "question": "How many 'arms' or points does a snowflake typically have?",
                "type": 'text',
                "options": [],
                "answer": '6',
                "lesson": 'Snowflakes almost always have 6 arms! This is because water molecules form hexagonal (6-sided) crystals as they freeze. No two snowflakes are exactly alike, but they nearly all share this beautiful 6-fold symmetry.',
                "xp": 15,
            },
            {
                "id": 'sym_square_lines',
                "question": 'How many lines of symmetry does a square have?',
                "type": 'quiz',
                "options": ['a) 1', 'b) 2', 'c) 4', 'd) 8'],
                "answer": 'c',
                "lesson": 'A square has 4 lines of symmetry — one vertical, one horizontal, and two diagonal. You can fold it along any of those 4 lines and both halves will match! A circle has the most lines of symmetry of any shape — infinitely many.',
                "xp": 10,
            },
            {
                "id": 'sym_next_in_pattern',
                "question": 'What comes next in this pattern? Star, heart, star, heart, star, _____',
                "type": 'text',
                "options": [],
                "answer": 'heart',
                "lesson": 'In this alternating pattern, star and heart take turns. So after star comes heart! Recognizing patterns is one of the most important skills in math and science. Your brain is actually a pattern-finding machine!',
                "xp": 15,
            },
            {
                "id": 'sym_rotational',
                "question": 'A pinwheel looks the same when you spin it around. What kind of symmetry is this?',
                "type": 'quiz',
                "options": ['a) Line symmetry', 'b) Rotational symmetry', 'c) Color symmetry', 'd) Asymmetry'],
                "answer": 'b',
                "lesson": 'Rotational symmetry means a shape looks the same after being turned (rotated) by a certain amount. A pinwheel, a starfish, and a Ferris wheel all have rotational symmetry. The more times it looks the same in a full turn, the more symmetry it has!',
                "xp": 10,
            },
        ],
    },
    "shapes_in_nature": {
        "id": "shapes_in_nature",
        "name": "The Nature Explorer's Trail",
        "description": 'Find circles, spirals, hexagons, and fractals hiding in the natural world!',
        "level_required": 1,
        "challenges": [
            {
                "id": 'nat_honeycomb',
                "question": 'Honeybees build their honeycombs using which shape?',
                "type": 'quiz',
                "options": ['a) Circles', 'b) Squares', 'c) Hexagons', 'd) Triangles'],
                "answer": 'c',
                "lesson": 'Bees build honeycombs from hexagons! Hexagons fit together with no gaps and use the least amount of wax to hold the most honey. Mathematicians have proven that hexagons are the most efficient shape for this — bees figured it out millions of years before humans did!',
                "xp": 10,
            },
            {
                "id": 'nat_spiral_shell',
                "question": "What shape do you see when you look at a snail's shell or a seashell from the side?",
                "type": 'quiz',
                "options": ['a) A square', 'b) A triangle', 'c) A spiral', 'd) A pentagon'],
                "answer": 'c',
                "lesson": 'Snail shells, seashells, and even galaxies form spirals! Many of these follow a special pattern called the Fibonacci spiral (or golden spiral), where each curve gets bigger by the same ratio. Hurricanes and sunflower seed patterns are spirals too!',
                "xp": 10,
            },
            {
                "id": 'nat_tree_fractal',
                "question": 'A tree trunk splits into branches, which split into smaller branches, which split into twigs. A pattern that repeats itself at smaller and smaller sizes is called a:',
                "type": 'quiz',
                "options": ['a) Fractal', 'b) Tessellation', 'c) Polygon', 'd) Prism'],
                "answer": 'a',
                "lesson": 'Fractals are patterns that repeat at every scale — big and small! Trees, ferns, broccoli, rivers, and even coastlines are natural fractals. If you zoom into a fractal, you see the same pattern again and again.',
                "xp": 10,
            },
            {
                "id": 'nat_rainbow_shape',
                "question": 'What shape is a rainbow? (Hint: it is half of a very common shape!)',
                "type": 'text',
                "options": [],
                "answer": 'semicircle',
                "lesson": 'A rainbow is a semicircle (half-circle)! From the ground we only see half, but if you were in an airplane, you could sometimes see a full circle rainbow. Rainbows form when sunlight enters raindrops and bounces around inside them.',
                "xp": 15,
            },
            {
                "id": 'nat_earth_shape',
                "question": 'What 3D shape is the Earth closest to?',
                "type": 'quiz',
                "options": ['a) A cube', 'b) A cylinder', 'c) A sphere', 'd) A cone'],
                "answer": 'c',
                "lesson": 'Earth is very close to a sphere! It is not a perfect sphere though — it bulges a tiny bit at the equator because of its spinning. The Sun, Moon, and most planets are also sphere-shaped because gravity pulls everything equally toward the center.',
                "xp": 10,
            },
            {
                "id": 'nat_spider_web',
                "question": 'A spider web often has lines going outward from the center like a bicycle wheel, plus circular threads connecting them. What is this web pattern called?',
                "type": 'quiz',
                "options": ['a) A grid pattern', 'b) A radial pattern', 'c) A zigzag pattern', 'd) A checkerboard pattern'],
                "answer": 'b',
                "lesson": 'Spider webs use a radial pattern — lines spreading outward from a center point, like spokes on a wheel. Radial patterns appear in flowers, starfish, and sliced oranges too. Spiders are amazing geometry engineers!',
                "xp": 10,
            },
            {
                "id": 'nat_bubbles_shape',
                "question": 'No matter what shape the bubble wand is, what shape does a soap bubble always become?',
                "type": 'quiz',
                "options": ['a) A cube', 'b) A sphere', 'c) The same shape as the wand', 'd) A cylinder'],
                "answer": 'b',
                "lesson": 'Soap bubbles always become spheres! A sphere has the smallest surface area for the amount of air inside — so the soap film naturally pulls itself into a ball shape. This is why bubbles, water droplets, and even planets are round!',
                "xp": 10,
            },
            {
                "id": 'nat_starfish_symmetry',
                "question": 'A starfish usually has how many arms?',
                "type": 'text',
                "options": [],
                "answer": '5',
                "lesson": 'Most starfish (sea stars) have 5 arms arranged with beautiful 5-fold radial symmetry. Some species can have up to 40 arms! If a starfish loses an arm, it can often grow a new one. Starfish show us that nature loves geometry — the 5-pointed star shape appears in flowers, fruits (slice an apple sideways!), and even sand dollars.',
                "xp": 15,
            },
        ],
    },
}
