"""
zones.py — Kindness zones and challenges.
"""

ZONE_ORDER = [
    "feelings_garden",
    "kindness_actions",
    "being_a_good_friend",
    "solving_problems",
    "listening_skills",
    "helping_community",
    "handling_hard_feelings",
]

ZONES = {
    "feelings_garden": {
        "id": "feelings_garden",
        "name": "The Feelings Garden",
        "subtitle": "Name your feelings, understand others",
        "icon": "🌸",
        "description": "Learn to identify and understand emotions",
        "level_required": 1,
        "challenges": [
            {
                "id": "fg_01",
                "title": "Happy",
                "type": "quiz",
                "question": "Your friend just got a puppy and is jumping up and down smiling. How does your friend feel?",
                "lesson": "[bold yellow]Happy[/bold yellow] is a feeling of joy and excitement. We feel happy when good things happen — getting a present, seeing a friend, hearing good news.",
                "options": ["Sad", "Scared", "Happy", "Angry"],
                "answer": "c",
                "hints": ["Jumping up and down with a smile — what does that look like?", "That's a happy feeling!"],
                "xp": 25,
            },
            {
                "id": "fg_02",
                "title": "Sad",
                "type": "quiz",
                "question": "Nell's goldfish died. She has tears in her eyes. How does Nell feel?",
                "lesson": "[bold yellow]Sad[/bold yellow] is a feeling that comes when we lose something we care about, or when things don't go the way we hoped. It's okay to feel sad.",
                "options": ["Happy", "Sad", "Surprised", "Bored"],
                "answer": "b",
                "hints": ["Tears are often a sign of this feeling.", "Losing someone you love makes you feel sad."],
                "xp": 25,
            },
            {
                "id": "fg_03",
                "title": "Angry",
                "type": "quiz",
                "question": "A kid at school takes your lunch without asking. Your face gets hot and your hands clench. How do you feel?",
                "lesson": "[bold yellow]Angry[/bold yellow] is a feeling that comes when something unfair happens or our boundaries are crossed. It's a normal feeling — what matters is how we handle it.",
                "options": ["Happy", "Sleepy", "Confused", "Angry"],
                "answer": "d",
                "hints": ["Hot face, clenched hands — your body is telling you something!", "That's an angry feeling — and it makes sense!"],
                "xp": 25,
            },
            {
                "id": "fg_04",
                "title": "Scared",
                "type": "quiz",
                "question": "It's dark outside and you hear a strange noise. Your heart beats fast. How do you feel?",
                "lesson": "[bold yellow]Scared[/bold yellow] (also called fear) is your body warning you to be careful. Your heart beats fast, you feel alert — it's your body trying to keep you safe.",
                "options": ["Bored", "Proud", "Scared", "Surprised"],
                "answer": "c",
                "hints": ["Heart beating fast in the dark — what feeling is that?", "Fear makes your heart speed up so you're ready to act!"],
                "xp": 25,
            },
            {
                "id": "fg_boss",
                "title": "Mixed Feelings",
                "type": "quiz",
                "question": "It's your first day at a new school. You're excited about new friends BUT nervous about not knowing anyone. What do you call this?",
                "lesson": "Sometimes we feel [bold yellow]more than one thing at once[/bold yellow]. Feeling both excited AND nervous at the same time is completely normal — it's sometimes called being [italic]anxiously excited[/italic]. Both feelings are real and valid!",
                "options": ["That's impossible — you can only feel one thing", "Happy", "Two feelings at once: excited and nervous", "Confused"],
                "answer": "c",
                "hints": ["Can your stomach feel butterflies from being both excited AND nervous?", "People feel multiple emotions at once all the time — and that's okay!"],
                "xp": 60,
                "is_boss": True,
            },
        ],
    },

    "kindness_actions": {
        "id": "kindness_actions",
        "name": "The Kindness Kitchen",
        "subtitle": "Small acts, big impact",
        "icon": "🤝",
        "description": "Practice choosing kind actions",
        "level_required": 2,
        "challenges": [
            {
                "id": "ka_01",
                "title": "Holding the Door",
                "type": "quiz",
                "question": "Someone is walking toward a door with their hands full of bags. What's the kind thing to do?",
                "lesson": "Small acts of [bold yellow]helping[/bold yellow] — like holding a door — cost us almost nothing but can mean a lot to someone who needs it. Kindness is often just noticing what someone needs.",
                "options": ["Walk through quickly before them", "Hold the door open for them", "Wait and see if they manage", "Ask if they need help, then walk away"],
                "answer": "b",
                "hints": ["They can't open the door easily with full hands!", "Holding the door is a small act that makes a real difference."],
                "xp": 30,
            },
            {
                "id": "ka_02",
                "title": "Sharing",
                "type": "quiz",
                "question": "You have 6 crackers. Your friend has none and looks hungry. What would be the kind thing to do?",
                "lesson": "[bold yellow]Sharing[/bold yellow] means giving some of what you have to someone who needs it. You don't have to give everything — even giving a little shows you care.",
                "options": ["Eat them all quickly", "Offer your friend some crackers", "Hide them so your friend doesn't see", "Ask a grown-up what to do"],
                "answer": "b",
                "hints": ["What would you hope a friend would do if the situation were reversed?", "Sharing a few crackers is a small kind act!"],
                "xp": 30,
            },
            {
                "id": "ka_03",
                "title": "Saying Thank You",
                "type": "quiz",
                "question": "Your teacher spent extra time helping you understand a hard problem. How do you show you appreciate it?",
                "lesson": "Saying [bold yellow]\"thank you\"[/bold yellow] sincerely tells people their effort mattered. A genuine thank-you makes people feel seen and valued — and it takes about two seconds.",
                "options": ["Just walk away when you're done", "Say thank you and mean it", "Nod quietly", "Tell your friends about it instead"],
                "answer": "b",
                "hints": ["How does it feel when someone genuinely thanks you?", "A real 'thank you' takes two seconds and means a lot!"],
                "xp": 30,
            },
            {
                "id": "ka_04",
                "title": "Including Others",
                "type": "quiz",
                "question": "You're playing a game at recess and you notice a new kid standing alone watching. What's the kind thing to do?",
                "lesson": "[bold yellow]Including people[/bold yellow] — inviting someone who is left out to join — is one of the most powerful acts of kindness. It can change how someone feels about their whole day.",
                "options": ["Keep playing — it's not your job to make friends for them", "Ask them if they want to play with you", "Ask your friend to talk to them instead", "Invite them tomorrow when you know them better"],
                "answer": "b",
                "hints": ["How would you feel if you were the new kid standing alone?", "An invitation to join changes everything!"],
                "xp": 35,
            },
            {
                "id": "ka_boss",
                "title": "Kindness When It's Hard",
                "type": "quiz",
                "question": "A kid who was mean to you yesterday fell off their bike and scraped their knee. What do you do?",
                "lesson": "True [bold yellow]kindness doesn't keep score[/bold yellow]. Helping someone who wasn't kind to you takes real strength — and it often breaks a cycle. It doesn't mean you forget what happened, but it means you choose to be a good person anyway.",
                "options": ["Walk past — they weren't nice to you", "Ask if they're okay and if they need help", "Tell others they fell", "Decide based on how you feel in the moment"],
                "answer": "b",
                "hints": ["Kindness given when it's hard means more than kindness given when it's easy.", "Helping someone who hurt you is one of the bravest kinds of kindness."],
                "xp": 70,
                "is_boss": True,
            },
        ],
    },

    "being_a_good_friend": {
        "id": "being_a_good_friend",
        "name": "The Friendship Forest",
        "subtitle": "What good friends do for each other",
        "icon": "🌳",
        "description": "Learn the skills of real friendship",
        "level_required": 3,
        "challenges": [
            {
                "id": "gf_01",
                "title": "Listening",
                "type": "quiz",
                "question": "Your friend is telling you about something exciting that happened to them. What does a good friend do?",
                "lesson": "[bold yellow]Listening[/bold yellow] means putting away your own thoughts for a moment and actually paying attention to what someone is saying. It's one of the greatest gifts you can give a friend.",
                "options": ["Think about what you want to say next", "Check if anyone more interesting is around", "Look at them, nod, and listen fully", "Wait for your turn and then talk about yourself"],
                "answer": "c",
                "hints": ["What makes you feel heard when you're talking to someone?", "Real listening means your full attention — not just waiting for your turn."],
                "xp": 30,
            },
            {
                "id": "gf_02",
                "title": "Honesty in Friendship",
                "type": "quiz",
                "question": "Your friend shows you a drawing they made and asks what you think. You think it needs work. What do you say?",
                "lesson": "Good friends tell the [bold yellow]kind truth[/bold yellow]. Not a harsh criticism — but not a dishonest compliment either. Something like: 'I love that you made this! The colors are great — maybe try making the person a bit bigger?' That's honest AND kind.",
                "options": ["'It's perfect!' even if it isn't", "'That's terrible, start over'", "Say something kind and honest — what you like and one helpful thought", "Say nothing and change the subject"],
                "answer": "c",
                "hints": ["Would you want your friend to tell you the truth if something needed work?", "Kind AND honest: notice what's good, then offer one helpful thought."],
                "xp": 35,
            },
            {
                "id": "gf_03",
                "title": "Being Happy for Your Friend",
                "type": "quiz",
                "question": "Your best friend wins first prize in the art competition, and you came in second. How does a good friend respond?",
                "lesson": "Being [bold yellow]genuinely happy for a friend's success[/bold yellow] — even when you wanted it too — is a real skill. It's called celebrating instead of being jealous. It takes practice, but it makes friendships much stronger.",
                "options": ["Pretend to be happy but complain later", "Tell everyone you should have won", "Congratulate them and mean it", "Avoid them for a while"],
                "answer": "c",
                "hints": ["How would you want your friend to react if you won and they came second?", "Genuine congratulations makes friendships stronger!"],
                "xp": 35,
            },
            {
                "id": "gf_04",
                "title": "Showing Up",
                "type": "quiz",
                "question": "Your friend's grandparent just died and they're sad. You don't know what to say. What do you do?",
                "lesson": "[bold yellow]Showing up[/bold yellow] matters more than saying the perfect thing. You don't need words to help — sitting with someone, giving a hug, or just saying 'I'm here' is often the most powerful thing a friend can do.",
                "options": ["Stay away because you don't know what to say", "Tell them it'll be okay even if you don't know that", "Be there with them — sit with them, hug them, say 'I'm here'", "Send a text instead of seeing them"],
                "answer": "c",
                "hints": ["When you're sad, what helps most — words or just having someone there?", "Being present is often more powerful than saying the right thing."],
                "xp": 35,
            },
            {
                "id": "gf_boss",
                "title": "When Friends Disagree",
                "type": "quiz",
                "question": "You and your best friend want to play different games. You can't agree. What's the best thing to do?",
                "lesson": "Good friends [bold yellow]compromise[/bold yellow] — each person gives a little. Maybe play one game today and the other tomorrow. Maybe each pick part of what you do. A compromise isn't about one person always giving in — it's about both people getting some of what they want.",
                "options": ["Play your game — it's better", "Give in completely and feel resentful", "Find a compromise where you each get some of what you want", "Ask a grown-up to decide for you"],
                "answer": "c",
                "hints": ["What if you played your friend's game today and yours tomorrow?", "Compromise = both people give a little, both people get something."],
                "xp": 70,
                "is_boss": True,
            },
        ],
    },

    "solving_problems": {
        "id": "solving_problems",
        "name": "The Bridge of Solutions",
        "subtitle": "Handle hard moments with grace",
        "icon": "🌉",
        "description": "Learn to handle conflict and hard situations",
        "level_required": 4,
        "challenges": [
            {
                "id": "sp_01",
                "title": "Taking a Breath",
                "type": "quiz",
                "question": "You're very angry about something. What's the smartest first thing to do?",
                "lesson": "When you're angry, your brain is flooded with emotion — [bold yellow]pausing and taking a slow breath[/bold yellow] gives your thinking brain a chance to catch up. It's not weakness. It's strategy.",
                "options": ["Say everything you're thinking immediately", "Walk away and never come back", "Take a slow breath and give yourself a moment to calm down", "Cry until it feels better"],
                "answer": "c",
                "hints": ["When you breathe slowly, what happens to your heart rate?", "A pause before you react often changes everything."],
                "xp": 30,
            },
            {
                "id": "sp_02",
                "title": "Using 'I Feel' Statements",
                "type": "quiz",
                "question": "Instead of saying 'You always ignore me!', a kinder way to say what you mean is:",
                "lesson": "[bold yellow]'I feel' statements[/bold yellow] tell people how YOU feel without attacking them. 'I feel ignored when you talk to other people during lunch' is easier to hear than an accusation — and more likely to actually help.",
                "options": ["'You never care about anyone but yourself'", "'I feel hurt when I feel left out'", "'Everyone agrees you're being mean'", "'Fine, forget it'"],
                "answer": "b",
                "hints": ["Which one says how you feel without blaming them directly?", "'I feel...' is easier to hear than 'You always...'"],
                "xp": 35,
            },
            {
                "id": "sp_03",
                "title": "Saying Sorry",
                "type": "quiz",
                "question": "You said something that hurt your friend's feelings by accident. What does a real apology include?",
                "lesson": "A real [bold yellow]apology[/bold yellow] has three parts: say what you did ('I said...'), acknowledge why it was wrong ('I know that hurt you'), and commit to doing better ('I'll be more careful'). Saying 'sorry you're upset' is NOT an apology.",
                "options": ["'Sorry if you felt bad'", "'I said something hurtful, I know that hurt you, and I'll be more careful'", "'I was just joking, you're too sensitive'", "'Whatever, sorry'"],
                "answer": "b",
                "hints": ["'Sorry you felt bad' puts the blame on them for having feelings. What does a real apology do?", "A real apology: what you did + why it was wrong + you'll do better."],
                "xp": 35,
            },
            {
                "id": "sp_04",
                "title": "Asking for Help",
                "type": "quiz",
                "question": "A problem feels too big to handle alone. What's the brave thing to do?",
                "lesson": "Asking for help is [bold yellow]brave, not weak[/bold yellow]. Everyone needs help sometimes — even grown-ups. Knowing when to ask for help, and asking clearly, is a skill that makes you stronger.",
                "options": ["Handle it alone no matter what", "Pretend everything is fine", "Ask someone you trust for help", "Give up on the problem"],
                "answer": "c",
                "hints": ["Has a grown-up ever asked for help with something? Does that make them weak?", "Asking for help when you need it is one of the smartest things you can do."],
                "xp": 30,
            },
            {
                "id": "sp_boss",
                "title": "When You Made a Mistake",
                "type": "quiz",
                "question": "You broke something by accident and now you're scared to tell the truth. What does a person of good character do?",
                "lesson": "[bold yellow]Integrity[/bold yellow] means doing the right thing even when no one is watching — and even when it's hard. Telling the truth when you've done something wrong, even when you're scared, builds trust and makes you the kind of person others can count on.",
                "options": ["Hide it and hope no one notices", "Blame someone else", "Tell the truth, say you're sorry, and offer to help fix it", "Wait and see if anyone figures it out"],
                "answer": "c",
                "hints": ["Telling the truth when it's scary is called integrity.", "What kind of person do you want to be? That's always the question."],
                "xp": 80,
                "is_boss": True,
            },
        ],
    },

    "listening_skills": {
        "id": "listening_skills",
        "name": "The Listening Garden",
        "subtitle": "Good listening is a superpower",
        "icon": "👂",
        "description": "Learn to truly listen and communicate with care",
        "level_required": 5,
        "challenges": [
            {
                "id": "ls_01",
                "title": "Eye Contact",
                "type": "quiz",
                "question": "Your friend is telling you something important. What does good listening look like?",
                "lesson": "When you look at someone while they talk, it tells them: [bold yellow]'I see you, and what you're saying matters to me.'[/bold yellow] You don't have to stare — just gently meeting someone's eyes says 'I'm here with you.'",
                "options": ["Look around the room to see what else is happening", "Stare at the floor so you can concentrate", "Look at them — meet their eyes gently while they speak", "Close your eyes to really focus on the words"],
                "answer": "c",
                "hints": ["How does it feel when someone looks at you while you're talking?", "Gentle eye contact says 'I'm listening' without a single word!"],
                "xp": 25,
            },
            {
                "id": "ls_02",
                "title": "Not Interrupting",
                "type": "quiz",
                "question": "Your friend is in the middle of telling a story and you just thought of something REALLY exciting to say. What should you do?",
                "lesson": "[bold yellow]Waiting for your turn[/bold yellow] shows respect. When you interrupt, the other person feels like their words don't matter. If you're worried you'll forget your idea, you can make a tiny mental note — but let them finish first.",
                "options": ["Jump in right away — your idea might be more interesting", "Walk away since your idea is urgent", "Wait for them to finish, then share your idea", "Talk over them quietly so they can still hear you"],
                "answer": "c",
                "hints": ["How does it feel when you're in the middle of something and someone cuts you off?", "Waiting your turn is a gift — it says 'your words matter to me.'"],
                "xp": 25,
            },
            {
                "id": "ls_03",
                "title": "Asking Good Questions",
                "type": "quiz",
                "question": "Your friend tells you they've been feeling sad lately. What's the kindest response?",
                "lesson": "Asking questions shows you really want to [bold yellow]understand[/bold yellow], not just hear. 'What's been making you feel sad?' or 'Do you want to talk about it?' invites your friend to share more — and that feels wonderful to someone who needs to be heard.",
                "options": ["Change the subject to something happier", "Tell them about a time you were sad", "Ask a question to understand better, like 'Do you want to talk about it?'", "Tell them to cheer up"],
                "answer": "c",
                "hints": ["Would you rather someone ask you questions or tell you how to feel?", "A question shows you care enough to understand — not just to respond!"],
                "xp": 30,
            },
            {
                "id": "ls_04",
                "title": "Repeating Back",
                "type": "quiz",
                "question": "After your friend explains a problem, you want to make sure you understood. What's a great thing to say?",
                "lesson": "[bold yellow]Reflecting back[/bold yellow] what you heard — 'So what I'm hearing is...' — is one of the most powerful listening skills there is. It shows you were paying attention, and it gives the other person a chance to correct you if you misunderstood.",
                "options": ["'I know exactly how you feel — the same thing happened to me!'", "'That sounds hard. So what I'm hearing is... did I get that right?'", "'I wasn't really listening, can you say it again?'", "'I'll tell you what I think you should do.'"],
                "answer": "b",
                "hints": ["Saying back what you heard checks that you really understood!", "'So what I'm hearing is...' is one of the kindest phrases you can use."],
                "xp": 30,
            },
            {
                "id": "ls_05",
                "title": "When You Disagree",
                "type": "quiz",
                "question": "Your friend says something you totally disagree with. What does a good listener do first?",
                "lesson": "Even when you disagree, [bold yellow]listen first[/bold yellow]. Let the other person finish. Try to understand why they think what they think. Then you can share your own view — calmly and kindly. Being heard first makes people much more willing to listen to you.",
                "options": ["Tell them immediately they're wrong", "Shake your head so they know you disagree while they're talking", "Listen all the way through, then calmly share your own view", "Walk away — no point in talking to someone who's wrong"],
                "answer": "c",
                "hints": ["When you feel heard, are you more or less willing to listen to someone else's side?", "Listen fully first — then share. That's how real conversations work."],
                "xp": 35,
            },
            {
                "id": "ls_boss",
                "title": "When Someone Needs to Talk",
                "type": "quiz",
                "question": "A friend is quieter than usual and seems far away. They haven't said anything is wrong. What might a good friend do?",
                "lesson": "Sometimes people need to be [bold yellow]invited[/bold yellow] to talk. They might not want to bother you, or they might not know how to start. A gentle 'Hey, are you okay? I'm here if you want to talk' can open a door that someone really needed opened.",
                "options": ["Leave them alone — if they wanted to talk they'd say so", "Tell them they look sad and ask what's wrong loudly", "Gently check in: 'Hey, you seem quiet — are you okay? I'm here if you want to talk'", "Tell other friends you're worried about them"],
                "answer": "c",
                "hints": ["Sometimes people need someone to notice before they can open up.", "A gentle, quiet check-in can mean everything to someone who's struggling."],
                "xp": 65,
                "is_boss": True,
            },
        ],
    },

    "helping_community": {
        "id": "helping_community",
        "name": "The Community Square",
        "subtitle": "How we take care of each other",
        "icon": "🏘️",
        "description": "Learn what a community is and how to give back",
        "level_required": 6,
        "challenges": [
            {
                "id": "hc_01",
                "title": "What Is a Community?",
                "type": "quiz",
                "question": "What makes a group of people a community?",
                "lesson": "A [bold yellow]community[/bold yellow] is a group of people who live in the same place or share something in common — and who look out for each other. Your neighborhood, your school, your family, and your class are all communities. You belong to many communities at once!",
                "options": ["A group of people who all look the same", "A group of people who live or work together and look out for each other", "Only the people who live on your street", "People who watch the same TV shows"],
                "answer": "b",
                "hints": ["Your classroom is a community — you all share it and look out for each other!", "Communities are about belonging together and caring for each other."],
                "xp": 25,
            },
            {
                "id": "hc_02",
                "title": "Helping Neighbors",
                "type": "quiz",
                "question": "Which of these is a real way a kid can help someone in their neighborhood?",
                "lesson": "You don't have to be grown-up to help your community! [bold yellow]Helping a neighbor[/bold yellow] can be as simple as picking up litter, holding a bag, waving hello to an elderly neighbor, or helping carry groceries. Small acts make neighborhoods kinder places.",
                "options": ["Nothing — kids are too small to help", "Only help if you get paid for it", "Pick up litter, wave hello, help carry something for someone who needs it", "Wait until you're older and then help"],
                "answer": "c",
                "hints": ["You've probably already helped a neighbor without thinking of it as a big thing!", "Even a wave and a smile to a lonely neighbor is real community care."],
                "xp": 25,
            },
            {
                "id": "hc_03",
                "title": "Why We Say Thank You",
                "type": "quiz",
                "question": "Why is it important to thank people who do things for us?",
                "lesson": "Saying [bold yellow]thank you[/bold yellow] tells someone their effort was seen and valued. People who feel appreciated are more likely to keep helping others. Gratitude is a little gift you give with words — and it costs nothing.",
                "options": ["It isn't really important — they did it anyway", "So they'll do more things for you later", "Because it tells people their effort mattered and makes them feel good", "To follow rules"],
                "answer": "c",
                "hints": ["Think about how YOU feel when someone genuinely thanks you.", "Gratitude sees people and says: 'What you did mattered.'"],
                "xp": 25,
            },
            {
                "id": "hc_04",
                "title": "Sharing vs Taking Turns",
                "type": "quiz",
                "question": "There's one swing at the playground and three kids want to use it. What's the fair thing to do?",
                "lesson": "[bold yellow]Taking turns[/bold yellow] means everyone gets a fair amount of time with something. Sharing means dividing what you have. When there's only one of something, taking turns is the kindest solution — everyone waits a little, and everyone gets a go.",
                "options": ["The fastest kid gets it", "The one who got there first keeps it as long as they want", "Everyone takes turns so each person gets a fair time", "Nobody uses it since it can't be shared equally"],
                "answer": "c",
                "hints": ["If everyone gets a turn, does anyone feel left out?", "Taking turns is sharing stretched over time — everyone gets something fair!"],
                "xp": 30,
            },
            {
                "id": "hc_05",
                "title": "What Fairness Means",
                "type": "quiz",
                "question": "Two kids are hungry. One is very hungry and one is a little hungry. You have 4 crackers. Fairness means giving them both 2 crackers each. But is there an even fairer way?",
                "lesson": "Fairness doesn't always mean [bold yellow]equal[/bold yellow] — sometimes it means giving people what they actually need. Giving 3 crackers to the very hungry child and 1 to the less hungry child might be fairer! Real fairness pays attention to what each person needs.",
                "options": ["Give them both 2 crackers each — equal is always fair", "Give all 4 to the most hungry child", "Think about what each person needs — maybe the hungrier one gets a bit more", "Eat them yourself since you can't decide"],
                "answer": "c",
                "hints": ["If one person needs a lot and one needs a little, does equal still feel fair?", "Real fairness is about meeting people's needs, not just dividing things in half."],
                "xp": 35,
            },
            {
                "id": "hc_boss",
                "title": "One Act That Costs Nothing",
                "type": "quiz",
                "question": "Which of these acts of kindness costs absolutely nothing but can still change someone's whole day?",
                "lesson": "The most powerful kindnesses often cost [bold yellow]nothing at all[/bold yellow]. A genuine smile. A 'good morning.' Noticing someone new and saying hello. Telling someone you appreciate them. These take seconds and can make a person feel like they matter — because they do.",
                "options": ["Buying someone a gift", "Doing someone else's chores for them", "Looking someone in the eyes and giving them a real, warm smile", "Lending someone money"],
                "answer": "c",
                "hints": ["Think of a time someone smiled at you warmly. How did it feel?", "A real smile says: 'I see you. You matter.' And it costs exactly nothing."],
                "xp": 65,
                "is_boss": True,
            },
        ],
    },

    "handling_hard_feelings": {
        "id": "handling_hard_feelings",
        "name": "The Feelings Workshop",
        "subtitle": "What to do when feelings get really big",
        "icon": "💛",
        "description": "Learn to handle big emotions with kindness toward yourself",
        "level_required": 7,
        "challenges": [
            {
                "id": "hf_01",
                "title": "When You're Angry",
                "type": "quiz",
                "question": "You feel really angry. Your face is hot and you want to shout. What's the smartest first step?",
                "lesson": "When you feel angry, your brain gets flooded with strong feelings. The first thing to do is [bold yellow]pause and breathe[/bold yellow]. Take a slow, deep breath. That gives your thinking brain a chance to catch up — and then you can decide what to do next. Pausing is not giving up. It's being smart.",
                "options": ["Shout out everything you're feeling right now", "Run away and never talk about it", "Pause and take a slow, deep breath first", "Pretend you're not angry"],
                "answer": "c",
                "hints": ["When you breathe slowly, your body actually starts to calm down!", "A pause before you react can change everything. It's your superpower."],
                "xp": 25,
            },
            {
                "id": "hf_02",
                "title": "Body Clues",
                "type": "quiz",
                "question": "Before a big test, your stomach feels tight and fluttery. What might that feeling mean?",
                "lesson": "Our bodies give us clues about our feelings! A [bold yellow]tight or fluttery stomach[/bold yellow] often means nervousness. A fast heartbeat can mean excitement or fear. Heavy shoulders might mean sadness or tiredness. When you notice what your body is doing, you get a clue about what you're feeling inside.",
                "options": ["You're probably sick and should go home", "You're probably nervous or anxious about the test", "Your stomach is just hungry", "You ate something bad for breakfast"],
                "answer": "b",
                "hints": ["Has your stomach ever felt like butterflies before something important?", "Your body is speaking to you — a fluttery stomach often means 'I'm nervous'!"],
                "xp": 25,
            },
            {
                "id": "hf_03",
                "title": "Crying Is Okay",
                "type": "quiz",
                "question": "You feel like crying but you're worried it will make you look weak. What's true about crying?",
                "lesson": "[bold yellow]Crying is completely okay[/bold yellow] — for everyone, at any age. Crying is your body's way of releasing strong feelings. It often helps you feel better afterward. There's nothing weak about it. In fact, being honest about your feelings takes real courage.",
                "options": ["Crying is only for babies and you should hold it in", "Crying means you're weak", "Crying is okay — it's a natural way your body releases big feelings", "You should only cry alone and never in front of anyone"],
                "answer": "c",
                "hints": ["Have you ever cried and then felt a little better afterward?", "Crying is your body's way of letting feelings out — it takes courage to let yourself feel."],
                "xp": 25,
            },
            {
                "id": "hf_04",
                "title": "Asking for Help",
                "type": "quiz",
                "question": "You're feeling overwhelmed — too many feelings at once and you don't know what to do. What's the brave thing?",
                "lesson": "When feelings are too big to handle alone, [bold yellow]asking for help[/bold yellow] is one of the bravest things you can do. A trusted grown-up, a friend, or even writing your feelings down can help. You don't have to carry big feelings by yourself.",
                "options": ["Handle it completely alone no matter what", "Pretend everything is fine until it passes", "Tell a trusted person how you're feeling and ask for help", "Give up trying to feel better"],
                "answer": "c",
                "hints": ["Asking for help with feelings is just as smart as asking for help with math!", "Everyone — even grown-ups — needs help with big feelings sometimes."],
                "xp": 30,
            },
            {
                "id": "hf_05",
                "title": "Being Kind to Yourself",
                "type": "quiz",
                "question": "You made a mistake and you're being very hard on yourself. What would Puck say?",
                "lesson": "[bold yellow]Being kind to yourself[/bold yellow] means speaking to yourself the way you'd speak to a good friend. If your friend made a mistake, you wouldn't say 'You're so stupid!' You'd say 'It's okay, everyone makes mistakes — what can you do next time?' Try saying that to yourself too.",
                "options": ["'I'm so stupid, I can't do anything right'", "'I should never try that again'", "'Everyone makes mistakes. What can I learn from this?'", "'I'll pretend it didn't happen'"],
                "answer": "c",
                "hints": ["Would you say harsh things to a friend who made a mistake?", "Speak to yourself like you'd speak to someone you love!"],
                "xp": 30,
            },
            {
                "id": "hf_boss",
                "title": "Sad vs Mean",
                "type": "quiz",
                "question": "Your friend snaps at you and says something hurtful. Later you find out they were having a terrible day. What's the difference between feeling sad and acting mean?",
                "lesson": "Feeling [bold yellow]sad, angry, or overwhelmed is not wrong[/bold yellow] — those are just feelings. But we are always responsible for how we treat others, even when we feel bad. 'I'm having a hard day' explains behavior but doesn't make it okay to be mean. The kind thing is to feel your feelings AND still choose how to treat people.",
                "options": ["When you feel bad, it's okay to be mean — people should understand", "Feelings and actions are the same thing", "Feelings are real and understandable, but we're still responsible for how we treat others", "If someone is mean it just means they're a bad person"],
                "answer": "c",
                "hints": ["Can you feel really angry AND still choose not to say something hurtful?", "Feelings are always okay — it's what we DO with them that matters."],
                "xp": 70,
                "is_boss": True,
            },
        ],
    },
}
