"""
zones.py — Kindness zones and challenges.
"""

ZONE_ORDER = [
    "feelings_garden",
    "kindness_actions",
    "being_a_good_friend",
    "solving_problems",
]

ZONES = {
    "feelings_garden": {
        "id": "feelings_garden",
        "name": "The Feelings Garden",
        "subtitle": "Name your feelings, understand others",
        "icon": "🌸",
        "description": "Learn to identify and understand emotions",
        "level_required": 1,
        "challenges": [
            {
                "id": "fg_01",
                "title": "Happy",
                "type": "quiz",
                "question": "Your friend just got a puppy and is jumping up and down smiling. How does your friend feel?",
                "lesson": "[bold yellow]Happy[/bold yellow] is a feeling of joy and excitement. We feel happy when good things happen — getting a present, seeing a friend, hearing good news.",
                "options": ["Sad", "Scared", "Happy", "Angry"],
                "answer": "c",
                "hints": ["Jumping up and down with a smile — what does that look like?", "That's a happy feeling!"],
                "xp": 25,
            },
            {
                "id": "fg_02",
                "title": "Sad",
                "type": "quiz",
                "question": "Nell's goldfish died. She has tears in her eyes. How does Nell feel?",
                "lesson": "[bold yellow]Sad[/bold yellow] is a feeling that comes when we lose something we care about, or when things don't go the way we hoped. It's okay to feel sad.",
                "options": ["Happy", "Sad", "Surprised", "Bored"],
                "answer": "b",
                "hints": ["Tears are often a sign of this feeling.", "Losing someone you love makes you feel sad."],
                "xp": 25,
            },
            {
                "id": "fg_03",
                "title": "Angry",
                "type": "quiz",
                "question": "A kid at school takes your lunch without asking. Your face gets hot and your hands clench. How do you feel?",
                "lesson": "[bold yellow]Angry[/bold yellow] is a feeling that comes when something unfair happens or our boundaries are crossed. It's a normal feeling — what matters is how we handle it.",
                "options": ["Happy", "Sleepy", "Confused", "Angry"],
                "answer": "d",
                "hints": ["Hot face, clenched hands — your body is telling you something!", "That's an angry feeling — and it makes sense!"],
                "xp": 25,
            },
            {
                "id": "fg_04",
                "title": "Scared",
                "type": "quiz",
                "question": "It's dark outside and you hear a strange noise. Your heart beats fast. How do you feel?",
                "lesson": "[bold yellow]Scared[/bold yellow] (also called fear) is your body warning you to be careful. Your heart beats fast, you feel alert — it's your body trying to keep you safe.",
                "options": ["Bored", "Proud", "Scared", "Surprised"],
                "answer": "c",
                "hints": ["Heart beating fast in the dark — what feeling is that?", "Fear makes your heart speed up so you're ready to act!"],
                "xp": 25,
            },
            {
                "id": "fg_boss",
                "title": "Mixed Feelings",
                "type": "quiz",
                "question": "It's your first day at a new school. You're excited about new friends BUT nervous about not knowing anyone. What do you call this?",
                "lesson": "Sometimes we feel [bold yellow]more than one thing at once[/bold yellow]. Feeling both excited AND nervous at the same time is completely normal — it's sometimes called being [italic]anxiously excited[/italic]. Both feelings are real and valid!",
                "options": ["That's impossible — you can only feel one thing", "Happy", "Two feelings at once: excited and nervous", "Confused"],
                "answer": "c",
                "hints": ["Can your stomach feel butterflies from being both excited AND nervous?", "People feel multiple emotions at once all the time — and that's okay!"],
                "xp": 60,
                "is_boss": True,
            },
        ],
    },

    "kindness_actions": {
        "id": "kindness_actions",
        "name": "The Kindness Kitchen",
        "subtitle": "Small acts, big impact",
        "icon": "🤝",
        "description": "Practice choosing kind actions",
        "level_required": 2,
        "challenges": [
            {
                "id": "ka_01",
                "title": "Holding the Door",
                "type": "quiz",
                "question": "Someone is walking toward a door with their hands full of bags. What's the kind thing to do?",
                "lesson": "Small acts of [bold yellow]helping[/bold yellow] — like holding a door — cost us almost nothing but can mean a lot to someone who needs it. Kindness is often just noticing what someone needs.",
                "options": ["Walk through quickly before them", "Hold the door open for them", "Wait and see if they manage", "Ask if they need help, then walk away"],
                "answer": "b",
                "hints": ["They can't open the door easily with full hands!", "Holding the door is a small act that makes a real difference."],
                "xp": 30,
            },
            {
                "id": "ka_02",
                "title": "Sharing",
                "type": "quiz",
                "question": "You have 6 crackers. Your friend has none and looks hungry. What would be the kind thing to do?",
                "lesson": "[bold yellow]Sharing[/bold yellow] means giving some of what you have to someone who needs it. You don't have to give everything — even giving a little shows you care.",
                "options": ["Eat them all quickly", "Offer your friend some crackers", "Hide them so your friend doesn't see", "Ask a grown-up what to do"],
                "answer": "b",
                "hints": ["What would you hope a friend would do if the situation were reversed?", "Sharing a few crackers is a small kind act!"],
                "xp": 30,
            },
            {
                "id": "ka_03",
                "title": "Saying Thank You",
                "type": "quiz",
                "question": "Your teacher spent extra time helping you understand a hard problem. How do you show you appreciate it?",
                "lesson": "Saying [bold yellow]\"thank you\"[/bold yellow] sincerely tells people their effort mattered. A genuine thank-you makes people feel seen and valued — and it takes about two seconds.",
                "options": ["Just walk away when you're done", "Say thank you and mean it", "Nod quietly", "Tell your friends about it instead"],
                "answer": "b",
                "hints": ["How does it feel when someone genuinely thanks you?", "A real 'thank you' takes two seconds and means a lot!"],
                "xp": 30,
            },
            {
                "id": "ka_04",
                "title": "Including Others",
                "type": "quiz",
                "question": "You're playing a game at recess and you notice a new kid standing alone watching. What's the kind thing to do?",
                "lesson": "[bold yellow]Including people[/bold yellow] — inviting someone who is left out to join — is one of the most powerful acts of kindness. It can change how someone feels about their whole day.",
                "options": ["Keep playing — it's not your job to make friends for them", "Ask them if they want to play with you", "Ask your friend to talk to them instead", "Invite them tomorrow when you know them better"],
                "answer": "b",
                "hints": ["How would you feel if you were the new kid standing alone?", "An invitation to join changes everything!"],
                "xp": 35,
            },
            {
                "id": "ka_boss",
                "title": "Kindness When It's Hard",
                "type": "quiz",
                "question": "A kid who was mean to you yesterday fell off their bike and scraped their knee. What do you do?",
                "lesson": "True [bold yellow]kindness doesn't keep score[/bold yellow]. Helping someone who wasn't kind to you takes real strength — and it often breaks a cycle. It doesn't mean you forget what happened, but it means you choose to be a good person anyway.",
                "options": ["Walk past — they weren't nice to you", "Ask if they're okay and if they need help", "Tell others they fell", "Decide based on how you feel in the moment"],
                "answer": "b",
                "hints": ["Kindness given when it's hard means more than kindness given when it's easy.", "Helping someone who hurt you is one of the bravest kinds of kindness."],
                "xp": 70,
                "is_boss": True,
            },
        ],
    },

    "being_a_good_friend": {
        "id": "being_a_good_friend",
        "name": "The Friendship Forest",
        "subtitle": "What good friends do for each other",
        "icon": "🌳",
        "description": "Learn the skills of real friendship",
        "level_required": 3,
        "challenges": [
            {
                "id": "gf_01",
                "title": "Listening",
                "type": "quiz",
                "question": "Your friend is telling you about something exciting that happened to them. What does a good friend do?",
                "lesson": "[bold yellow]Listening[/bold yellow] means putting away your own thoughts for a moment and actually paying attention to what someone is saying. It's one of the greatest gifts you can give a friend.",
                "options": ["Think about what you want to say next", "Check if anyone more interesting is around", "Look at them, nod, and listen fully", "Wait for your turn and then talk about yourself"],
                "answer": "c",
                "hints": ["What makes you feel heard when you're talking to someone?", "Real listening means your full attention — not just waiting for your turn."],
                "xp": 30,
            },
            {
                "id": "gf_02",
                "title": "Honesty in Friendship",
                "type": "quiz",
                "question": "Your friend shows you a drawing they made and asks what you think. You think it needs work. What do you say?",
                "lesson": "Good friends tell the [bold yellow]kind truth[/bold yellow]. Not a harsh criticism — but not a dishonest compliment either. Something like: 'I love that you made this! The colors are great — maybe try making the person a bit bigger?' That's honest AND kind.",
                "options": ["'It's perfect!' even if it isn't", "'That's terrible, start over'", "Say something kind and honest — what you like and one helpful thought", "Say nothing and change the subject"],
                "answer": "c",
                "hints": ["Would you want your friend to tell you the truth if something needed work?", "Kind AND honest: notice what's good, then offer one helpful thought."],
                "xp": 35,
            },
            {
                "id": "gf_03",
                "title": "Being Happy for Your Friend",
                "type": "quiz",
                "question": "Your best friend wins first prize in the art competition, and you came in second. How does a good friend respond?",
                "lesson": "Being [bold yellow]genuinely happy for a friend's success[/bold yellow] — even when you wanted it too — is a real skill. It's called celebrating instead of being jealous. It takes practice, but it makes friendships much stronger.",
                "options": ["Pretend to be happy but complain later", "Tell everyone you should have won", "Congratulate them and mean it", "Avoid them for a while"],
                "answer": "c",
                "hints": ["How would you want your friend to react if you won and they came second?", "Genuine congratulations makes friendships stronger!"],
                "xp": 35,
            },
            {
                "id": "gf_04",
                "title": "Showing Up",
                "type": "quiz",
                "question": "Your friend's grandparent just died and they're sad. You don't know what to say. What do you do?",
                "lesson": "[bold yellow]Showing up[/bold yellow] matters more than saying the perfect thing. You don't need words to help — sitting with someone, giving a hug, or just saying 'I'm here' is often the most powerful thing a friend can do.",
                "options": ["Stay away because you don't know what to say", "Tell them it'll be okay even if you don't know that", "Be there with them — sit with them, hug them, say 'I'm here'", "Send a text instead of seeing them"],
                "answer": "c",
                "hints": ["When you're sad, what helps most — words or just having someone there?", "Being present is often more powerful than saying the right thing."],
                "xp": 35,
            },
            {
                "id": "gf_boss",
                "title": "When Friends Disagree",
                "type": "quiz",
                "question": "You and your best friend want to play different games. You can't agree. What's the best thing to do?",
                "lesson": "Good friends [bold yellow]compromise[/bold yellow] — each person gives a little. Maybe play one game today and the other tomorrow. Maybe each pick part of what you do. A compromise isn't about one person always giving in — it's about both people getting some of what they want.",
                "options": ["Play your game — it's better", "Give in completely and feel resentful", "Find a compromise where you each get some of what you want", "Ask a grown-up to decide for you"],
                "answer": "c",
                "hints": ["What if you played your friend's game today and yours tomorrow?", "Compromise = both people give a little, both people get something."],
                "xp": 70,
                "is_boss": True,
            },
        ],
    },

    "solving_problems": {
        "id": "solving_problems",
        "name": "The Bridge of Solutions",
        "subtitle": "Handle hard moments with grace",
        "icon": "🌉",
        "description": "Learn to handle conflict and hard situations",
        "level_required": 4,
        "challenges": [
            {
                "id": "sp_01",
                "title": "Taking a Breath",
                "type": "quiz",
                "question": "You're very angry about something. What's the smartest first thing to do?",
                "lesson": "When you're angry, your brain is flooded with emotion — [bold yellow]pausing and taking a slow breath[/bold yellow] gives your thinking brain a chance to catch up. It's not weakness. It's strategy.",
                "options": ["Say everything you're thinking immediately", "Walk away and never come back", "Take a slow breath and give yourself a moment to calm down", "Cry until it feels better"],
                "answer": "c",
                "hints": ["When you breathe slowly, what happens to your heart rate?", "A pause before you react often changes everything."],
                "xp": 30,
            },
            {
                "id": "sp_02",
                "title": "Using 'I Feel' Statements",
                "type": "quiz",
                "question": "Instead of saying 'You always ignore me!', a kinder way to say what you mean is:",
                "lesson": "[bold yellow]'I feel' statements[/bold yellow] tell people how YOU feel without attacking them. 'I feel ignored when you talk to other people during lunch' is easier to hear than an accusation — and more likely to actually help.",
                "options": ["'You never care about anyone but yourself'", "'I feel hurt when I feel left out'", "'Everyone agrees you're being mean'", "'Fine, forget it'"],
                "answer": "b",
                "hints": ["Which one says how you feel without blaming them directly?", "'I feel...' is easier to hear than 'You always...'"],
                "xp": 35,
            },
            {
                "id": "sp_03",
                "title": "Saying Sorry",
                "type": "quiz",
                "question": "You said something that hurt your friend's feelings by accident. What does a real apology include?",
                "lesson": "A real [bold yellow]apology[/bold yellow] has three parts: say what you did ('I said...'), acknowledge why it was wrong ('I know that hurt you'), and commit to doing better ('I'll be more careful'). Saying 'sorry you're upset' is NOT an apology.",
                "options": ["'Sorry if you felt bad'", "'I said something hurtful, I know that hurt you, and I'll be more careful'", "'I was just joking, you're too sensitive'", "'Whatever, sorry'"],
                "answer": "b",
                "hints": ["'Sorry you felt bad' puts the blame on them for having feelings. What does a real apology do?", "A real apology: what you did + why it was wrong + you'll do better."],
                "xp": 35,
            },
            {
                "id": "sp_04",
                "title": "Asking for Help",
                "type": "quiz",
                "question": "A problem feels too big to handle alone. What's the brave thing to do?",
                "lesson": "Asking for help is [bold yellow]brave, not weak[/bold yellow]. Everyone needs help sometimes — even grown-ups. Knowing when to ask for help, and asking clearly, is a skill that makes you stronger.",
                "options": ["Handle it alone no matter what", "Pretend everything is fine", "Ask someone you trust for help", "Give up on the problem"],
                "answer": "c",
                "hints": ["Has a grown-up ever asked for help with something? Does that make them weak?", "Asking for help when you need it is one of the smartest things you can do."],
                "xp": 30,
            },
            {
                "id": "sp_boss",
                "title": "When You Made a Mistake",
                "type": "quiz",
                "question": "You broke something by accident and now you're scared to tell the truth. What does a person of good character do?",
                "lesson": "[bold yellow]Integrity[/bold yellow] means doing the right thing even when no one is watching — and even when it's hard. Telling the truth when you've done something wrong, even when you're scared, builds trust and makes you the kind of person others can count on.",
                "options": ["Hide it and hope no one notices", "Blame someone else", "Tell the truth, say you're sorry, and offer to help fix it", "Wait and see if anyone figures it out"],
                "answer": "c",
                "hints": ["Telling the truth when it's scary is called integrity.", "What kind of person do you want to be? That's always the question."],
                "xp": 80,
                "is_boss": True,
            },
        ],
    },
}
